@extends('layouts.app')

@section('content')
<x-waggies.breadcrumb-strip :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Pricing', 'route' => 'services.pricing']]" class="bg-white border-b border-primary/5" />
<x-waggies.page-header align="center" eyebrow="Transparent Pricing" title="Simple, Honest Pricing" subtitle="No hidden fees. Use our estimator for a tailored quote, then book or speak with our team." />

<section id="pricing-calculator" x-data="pricingCalculator(@js($pricing), @js($resolved), @js(route('contact')))" class="scroll-mt-24 bg-surface-purple py-16">
    <div class="mx-auto max-w-5xl px-4 md:px-10 lg:px-12">
        <x-waggies.section-heading eyebrow="Pricing Tool" title="Get Your Estimate" subtitle="Select your service and package - we'll show a clear price or quote range and next steps." />
        <div x-show="step === 'form'" x-transition class="mt-10 rounded-2xl border border-surface-purple bg-white p-6 shadow-soft md:p-8">
            <div class="flex flex-col gap-5">
                <template x-if="!locked"><label class="text-sm font-semibold">Service<select x-model="service" @change="variant=''; tier=''" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"><option value="">Choose a service…</option><template x-for="(item,key) in services" :key="key"><option :value="key" x-text="item.label"></option></template></select></label></template>
                <template x-if="locked && current"><div><p class="text-sm font-semibold text-primary-dark/60">Service</p><p class="text-lg font-bold" x-text="current.label"></p></div></template>
                <template x-if="hasVariants"><label class="text-sm font-semibold">Pet type<select x-model="variant" @change="tier=''" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"><option value="">Choose…</option><template x-for="(item,key) in current.variants" :key="key"><option :value="key" x-text="item.label"></option></template></select></label></template>
                <template x-if="isLocalTransport"><div class="flex flex-col gap-4 rounded-xl border border-surface-purple p-4"><p class="text-xs font-bold uppercase tracking-wider text-primary/60">Route details</p><div class="grid grid-cols-1 gap-4 sm:grid-cols-2"><label class="text-sm font-semibold text-primary-dark">Pickup location<input x-model="transportValues.origin" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label><label class="text-sm font-semibold text-primary-dark">Drop-off location<input x-model="transportValues.destination" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label><label class="text-sm font-semibold text-primary-dark">Distance (km)<input x-model="transportValues.distanceKm" type="number" min="1" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label><label class="text-sm font-semibold text-primary-dark">Pet species<input x-model="transportValues.petSpecies" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label><label class="text-sm font-semibold text-primary-dark">Pet count<input x-model="transportValues.petCount" type="number" min="1" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label><label class="text-sm font-semibold text-primary-dark">Journey<select x-model="transportValues.journeyType" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"><option value="one-way">One-way</option><option value="return">Return</option></select></label><template x-if="tier === 'airport'"><label class="text-sm font-semibold text-primary-dark">Airport details<input x-model="transportValues.airportDetails" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label></template></div><p class="text-xs text-primary-dark/60">Special handling, extra stops, waiting, urgency, and after-hours requests may require a quote.</p></div></template>
                <template x-if="tierOptions.length"><div><p class="mb-2 text-sm font-semibold">Package</p><div class="grid grid-cols-1 gap-3 sm:grid-cols-2"><template x-for="item in tierOptions" :key="item.key"><button type="button" @click="tier=item.key" :aria-pressed="tier === item.key" :class="tier === item.key ? 'border-primary bg-primary/5 shadow-sm' : 'border-surface-purple bg-white hover:border-primary/40'" class="relative overflow-hidden rounded-xl border-2 p-4 text-left transition"><div class="flex items-start justify-between gap-2"><div><p class="text-sm font-bold" x-text="item.label"></p><p class="mt-0.5 text-xs text-primary-dark/60" x-text="price(item)"></p></div><span x-show="item.badge" class="shrink-0 rounded-full bg-primary/10 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-primary" x-text="item.badge"></span></div><span x-show="tier === item.key" class="absolute right-3 top-3 flex h-5 w-5 items-center justify-center rounded-full bg-primary text-white"><x-waggies.icon name="check" size="14" /></span></button></template></div></div></template>
                <template x-if="current && current.quantity_label"><label class="text-sm font-semibold"><span x-text="current.quantity_label"></span><input x-model.number="quantity" type="number" min="1" max="30" class="mt-2 w-full rounded-xl border border-surface-purple px-4 py-3 font-normal"></label></template>
                <button type="button" @click="calculate()" :disabled="!canCalculate" class="w-cta w-cta--primary w-full justify-center sm:w-auto" x-text="actionLabel"></button>
            </div>
        </div>
        <div x-show="step === 'result'" x-transition class="mt-10 overflow-hidden rounded-2xl border-2 border-primary bg-white shadow-soft">
            <div class="grid grid-cols-1 lg:grid-cols-[1.4fr_1fr]"><div class="border-b border-surface-purple p-6 md:p-8 lg:border-b-0 lg:border-r"><p class="mb-2 text-xs font-bold uppercase tracking-widest text-primary/60">Your estimate</p><p class="text-sm text-primary-dark/60" x-text="result.service"></p><p class="mb-6 text-sm text-primary-dark/50" x-text="result.tier"></p><h3 class="mb-4 flex items-center gap-2 font-serif text-lg font-bold"><x-waggies.icon name="checklist" size="20" class="text-primary" />What's included</h3><ul class="space-y-2.5"><template x-for="(feature,index) in result.features" :key="index"><li class="flex items-start gap-2.5 text-sm"><span class="mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-success/15 text-success"><x-waggies.icon name="check" size="14" /></span><span x-text="typeof feature === 'string' ? feature : feature.label"></span></li></template></ul><button type="button" @click="reset()" class="mt-6 inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline"><x-waggies.icon name="arrow-back" size="16" />Start over</button></div><div class="bg-surface-purple/40 p-6 md:p-8 lg:sticky lg:top-24 lg:self-start"><p class="mb-3 text-xs font-bold uppercase tracking-widest text-primary/60">Price summary</p><p class="mb-2 font-serif text-3xl font-bold md:text-4xl" x-html="result.display"></p><p class="mb-1 text-sm text-primary-dark/60" x-text="result.tier"></p><p class="mb-5 text-xs text-primary-dark/60" x-text="result.service"></p><p x-show="result.notice" class="mb-5 text-xs text-primary-dark/60" x-text="result.notice"></p><div class="flex flex-col gap-3"><a :href="result.href" class="w-cta w-cta--primary w-full justify-center"><span x-text="result.cta"></span><x-waggies.icon name="arrow-forward" size="16" /></a></div></div></div>
        </div>
    </div>
</section>

<section class="bg-white py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><x-waggies.section-heading eyebrow="Boarding" title="Overnight Boarding" />@foreach($pricing['services']['boarding']['variants'] as $variantKey => $variant)<div><h3 class="mb-6 mt-10 font-serif text-2xl font-bold text-primary-dark">{{ $variant['label'] }}</h3><div class="grid grid-cols-1 gap-8 md:grid-cols-3">@foreach($variant['tiers'] as $tierKey => $tier)<x-waggies.pricing-tier-card :tier="$tier" unit="/night" service-key="boarding" :variant-key="$variantKey" :tier-key="$tierKey" />@endforeach</div></div>@endforeach</div></section>
<section class="bg-surface-purple py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><x-waggies.section-heading eyebrow="Grooming" title="Grooming Packages" /><div class="mt-10 grid grid-cols-1 gap-8 md:grid-cols-3">@foreach($pricing['services']['grooming']['tiers'] as $tierKey => $tier)<x-waggies.pricing-tier-card :tier="$tier" unit="/session" service-key="grooming" :tier-key="$tierKey" />@endforeach</div></div></section>
<section class="bg-white py-16"><div class="mx-auto max-w-3xl px-4 text-center"><h2 class="mb-3 font-serif text-3xl font-bold text-primary-dark md:text-4xl">Training, vet care, or relocation?</h2><p class="mb-8 text-primary-dark/60">Jump straight to the service you need. The estimator pre-selects your choice where pricing is published; quote-based services route to the request form so Waggies can confirm pricing.</p><div class="grid grid-cols-1 gap-4 sm:grid-cols-3"><a href="{{ route('services.pricing', ['service' => 'training']) }}" class="group flex flex-col items-center gap-3 rounded-2xl border-2 border-surface-purple bg-white p-6 transition hover:border-primary hover:shadow-sm"><span class="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary"><x-waggies.icon name="dog" size="24" /></span><span class="text-sm font-bold">Estimate Training Cost</span></a><a href="{{ route('contact', ['intent' => 'veterinary', 'service' => 'vet-care']) }}" class="group flex flex-col items-center gap-3 rounded-2xl border-2 border-surface-purple bg-white p-6 transition hover:border-primary hover:shadow-sm"><span class="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary"><x-waggies.icon name="favorite" size="24" /></span><span class="text-sm font-bold">Request Vet Care Quote</span></a><a href="{{ route('services.pricing', ['service' => 'relocation']) }}" class="group flex flex-col items-center gap-3 rounded-2xl border-2 border-surface-purple bg-white p-6 transition hover:border-primary hover:shadow-sm"><span class="flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 text-primary"><x-waggies.icon name="relocation" size="24" /></span><span class="text-sm font-bold">Estimate Relocation Cost</span></a></div></div></section>
@endsection
