@extends('layouts.app')

@section('content')
<x-waggies.breadcrumb-strip :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Pet Relocation', 'route' => 'services.relocation']]" />

<x-waggies.cover-hero :hero="array_merge($hero, ['eyebrow' => 'International & Local Relocation', 'eyebrowIcon' => 'airport-departure', 'title' => 'Stress-Free Pet Relocation<br/>Home & Abroad', 'subtitle' => 'End-to-end relocation management for pets moving into, out of, or across Nigeria. Permits, vet endorsements, IATA crates, and flight coordination handled with total precision.', 'cta' => ['label' => 'Request Relocation Quote', 'route' => 'contact', 'params' => ['intent' => 'quote', 'service' => 'relocation'], 'icon' => 'arrow-forward'], 'secondaryCta' => ['label' => 'Explore Relocation Hub', 'route' => 'services.relocation']])" title-id="hero-image-title" :center="true" />

<section class="bg-white py-20">
    <div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12">
        <div class="mb-12 max-w-3xl"><span class="text-eyebrow mb-2 block">Relocation Capabilities</span><h2 class="text-h2">Comprehensive Transport &amp; Relocation Services</h2><p class="mt-3 text-primary-dark/60">Whether moving across Abuja or relocating across continents, our certified specialists ensure your pet travels safely, comfortably, and legally.</p></div>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-3">@foreach($cards as $card)<x-waggies.service-card :card="$card" />@endforeach</div>

        <div class="mt-14 overflow-hidden rounded-2xl border border-primary/10 bg-surface-purple/40"><div class="grid grid-cols-1 md:grid-cols-2"><div class="relative min-h-[220px] overflow-hidden md:h-auto"><img src="https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=600&fit=crop&q=80" alt="Pet relocation document checklist" loading="lazy" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-primary-dark/20" aria-hidden="true"></div></div><div class="flex flex-col justify-center p-8 md:p-10"><span class="text-eyebrow mb-2 block">Planning Tool</span><h3 class="mb-3 font-serif text-2xl font-bold text-primary-dark">Relocation Preparation Checklist</h3><p class="mb-5 text-sm leading-relaxed text-primary-dark/70">Plan your pet&apos;s relocation timeline with our interactive checklist. Track required vaccinations, microchipping, rabies titer blood tests, and import/export documentation steps.</p><ul class="mb-6 space-y-2 text-xs text-primary-dark/75"><li class="flex items-center gap-2"><x-waggies.icon name="check-circle" size="16" variant="filled" class="shrink-0 text-primary" />Month-by-month relocation schedule</li><li class="flex items-center gap-2"><x-waggies.icon name="check-circle" size="16" variant="filled" class="shrink-0 text-primary" />Country-specific health certificate guidelines</li><li class="flex items-center gap-2"><x-waggies.icon name="check-circle" size="16" variant="filled" class="shrink-0 text-primary" />IATA crate dimension &amp; ventilation standards</li></ul><a href="{{ route('relocation.checklist') }}" class="w-cta w-cta--primary w-fit">Open Relocation Checklist <x-waggies.icon name="arrow-forward" size="16" /></a></div></div></div>
    </div>
</section>

<section class="border-t border-primary/5 bg-surface py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><div class="mx-auto mb-14 max-w-xl text-center"><span class="text-eyebrow mb-2 block">Methodology</span><h2 class="text-h2">How We Manage Your Pet&apos;s Relocation</h2><p class="text-body-sm text-primary-dark/70">Four methodical steps to eliminate bureaucratic delays and ensure smooth transit.</p></div><div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">@foreach([['01','Route & Permit Audit','We analyze your destination country regulations, timeline constraints, and manage Ministry import/export permit applications.'],['02','Veterinary Compliance','Coordinate microchipping, rabies blood titer testing, required vaccinations, and official government health endorsements.'],['03','IATA Crate & Flight Booking','Custom sizing and assembly of IATA-compliant travel containers and direct booking on approved pet-friendly airlines.'],['04','Customs & Door-to-Door Delivery','Complete customs clearance at Abuja airport, tarmac handling oversight, and air-conditioned transfer straight to your door.']] as $step)<div class="w-card flex flex-col justify-between rounded-2xl border border-primary/10 bg-white p-6"><div><span class="mb-3 block font-serif text-3xl font-bold text-primary/30">{{ $step[0] }}</span><h3 class="mb-2 font-serif text-lg font-bold text-primary-dark">{{ $step[1] }}</h3><p class="text-xs leading-relaxed text-primary-dark/65">{{ $step[2] }}</p></div></div>@endforeach</div></div></section>

<x-waggies.proof-band variant="relocation" />

<section class="border-t border-primary/5 bg-white py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><div class="mb-14 text-center"><span class="text-eyebrow mb-2 block">Frequent Questions</span><h2 class="text-h2">Frequently Asked Questions About Relocation</h2><p class="mx-auto max-w-2xl text-primary-dark/60">Clear answers on documentation, timelines, flight requirements, and pet safety during transit.</p></div><x-waggies.faq-accordion :faqs="$faqs" /><p class="mt-8 text-center text-sm text-primary-dark/60">Have specific country requirements? <a href="{{ route('contact') }}" class="font-bold text-primary hover:underline">Contact our relocation specialists</a> for direct assistance.</p></div></section>

<section class="w-full py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><div class="w-full rounded-2xl bg-primary-dark"><div class="mx-auto flex max-w-5xl flex-col gap-10 px-4 py-12 md:flex-row md:items-center md:justify-between md:px-10 md:py-16 lg:px-12"><div class="flex max-w-xl flex-col items-center gap-5 text-center md:items-start md:text-left"><h2 class="font-serif text-3xl font-bold leading-tight text-white md:text-4xl">Planning Your Pet’s Move?<br/><span class="text-secondary italic">Let Our Experts Handle the Details</span></h2><p class="max-w-sm text-base leading-relaxed text-white/65 md:max-w-md">From official Ministry permits to airline cargo reservations and customs clearance, Waggies makes relocation simple and secure.</p></div><div class="flex flex-wrap justify-center gap-3 md:items-center md:justify-end"><a href="{{ route('contact', ['intent' => 'quote', 'service' => 'relocation']) }}" class="w-cta w-cta--primary !bg-secondary !text-primary-dark">Request Relocation Quote <x-waggies.icon name="arrow-forward" size="16" /></a><a href="{{ route('services.relocation') }}" class="w-cta w-cta--secondary border-white/30 bg-transparent text-white hover:bg-white/10"><x-waggies.icon name="global" size="16" />Explore Relocation Hub</a></div></div></div></div></section>

@endsection
