@extends('layouts.app')

@section('content')
<x-waggies.breadcrumb-strip :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Pet Relocation', 'route' => 'services.relocation']]" />

<x-waggies.cover-hero :hero="array_merge($hero, ['eyebrow' => 'International & Local Relocation', 'eyebrowIcon' => 'airport-departure', 'title' => 'Stress-Free Pet Relocation<br/>Home & Abroad', 'description' => 'End-to-end relocation management for pets moving into, out of, or across Nigeria. Permits, vet endorsements, IATA crates, and flight coordination handled with total precision.', 'actions' => [['label' => 'Request Relocation Quote', 'url' => route('contact', ['intent' => 'quote', 'service' => 'relocation']), 'icon' => 'arrow-forward'], ['label' => 'Open Relocation Checklist', 'url' => route('relocation.checklist'), 'icon' => 'checklist']]])" />

<section class="bg-white py-20">
    <div class="page-container">
        <div class="mb-12 max-w-3xl"><span class="text-eyebrow mb-2 block">Relocation Capabilities</span><h2 class="text-h2">Comprehensive Transport &amp; Relocation Services</h2><p class="mt-3 text-primary-dark/60">Whether moving across Abuja or relocating across continents, our certified specialists ensure your pet travels safely, comfortably, and legally.</p></div>
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-3">@foreach($cards as $card)<x-waggies.service-card :card="$card" />@endforeach</div>

        <div class="mt-14 overflow-hidden rounded-2xl border border-primary/10 bg-surface-purple/40"><div class="grid grid-cols-1 md:grid-cols-2"><div class="relative min-h-[220px] overflow-hidden md:h-auto"><img src="/media/services/relocation/checklist/hero.jpg" alt="Pet relocation document checklist" loading="lazy" class="absolute inset-0 h-full w-full object-cover"><div class="absolute inset-0 bg-primary-dark/20" aria-hidden="true"></div></div><div class="flex flex-col justify-center p-8 md:p-10"><span class="text-eyebrow mb-2 block">Planning Tool</span><h3 class="mb-3 font-serif text-2xl font-bold text-primary-dark">Relocation Preparation Checklist</h3><p class="mb-5 text-sm leading-relaxed text-primary-dark/70">Plan your pet&apos;s relocation timeline with our interactive checklist. Track required vaccinations, microchipping, rabies titer blood tests, and import/export documentation steps.</p><ul class="mb-6 space-y-2 text-xs text-primary-dark/75"><li class="flex items-center gap-2"><x-waggies.icon name="check-circle" size="16" variant="filled" class="shrink-0 text-primary" />Month-by-month relocation schedule</li><li class="flex items-center gap-2"><x-waggies.icon name="check-circle" size="16" variant="filled" class="shrink-0 text-primary" />Country-specific health certificate guidelines</li><li class="flex items-center gap-2"><x-waggies.icon name="check-circle" size="16" variant="filled" class="shrink-0 text-primary" />IATA crate dimension &amp; ventilation standards</li></ul><x-waggies.button href="{{ route('relocation.checklist') }}" class="w-fit">Open Relocation Checklist <x-waggies.icon name="arrow-forward" size="16" /></x-waggies.button></div></div></div>
    </div>
</section>

<section class="border-t border-primary/5 bg-surface py-20"><div class="page-container"><div class="mx-auto mb-14 max-w-xl text-center"><span class="text-eyebrow mb-2 block">Methodology</span><h2 class="text-h2">How We Manage Your Pet&apos;s Relocation</h2><p class="text-body-sm text-primary-dark/70">Four methodical steps to eliminate bureaucratic delays and ensure smooth transit.</p></div><ol class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">@foreach([['01','Route & Permit Audit','We analyze your destination country regulations, timeline constraints, and manage Ministry import/export permit applications.'],['02','Veterinary Compliance','Coordinate microchipping, rabies blood titer testing, required vaccinations, and official government health endorsements.'],['03','IATA Crate & Flight Booking','Custom sizing and assembly of IATA-compliant travel containers and direct booking on approved pet-friendly airlines.'],['04','Customs & Door-to-Door Delivery','Complete customs clearance at Abuja airport, tarmac handling oversight, and air-conditioned transfer straight to your door.']] as $step)<li class="w-card flex flex-col justify-between rounded-2xl border border-primary/10 bg-white p-6"><div><span class="mb-3 block font-serif text-3xl font-bold text-primary/30">{{ $step[0] }}</span><h3 class="mb-2 font-serif text-lg font-bold text-primary-dark">{{ $step[1] }}</h3><p class="text-xs leading-relaxed text-primary-dark/65">{{ $step[2] }}</p></div></li>@endforeach</ol></div></section>

<x-waggies.proof-band variant="relocation" />

<section class="border-t border-primary/5 bg-white py-20"><div class="page-container"><x-waggies.section-heading eyebrow="Frequent Questions" title="Frequently Asked Questions About Relocation" subtitle="Clear answers on documentation, timelines, flight requirements, and pet safety during transit." spacing="mb-14" /><x-waggies.faq-accordion :faqs="$faqs" /><p class="mt-8 text-center text-sm text-primary-dark/60">Have specific country requirements? <a href="{{ route('contact') }}" class="font-bold text-primary hover:underline">Contact our relocation specialists</a> for direct assistance.</p></div></section>

@php($relocationCta = ['heading' => 'Planning Your Pet’s Move?', 'headingAccent' => 'Let Our Experts Handle the Details', 'body' => 'From official Ministry permits to airline cargo reservations and customs clearance, Waggies makes relocation simple and secure.', 'primaryLabel' => 'Request Relocation Quote', 'primaryRoute' => 'contact', 'primaryParams' => ['intent' => 'quote', 'service' => 'relocation'], 'secondaryLabel' => 'Open Relocation Checklist', 'secondaryRoute' => 'relocation.checklist', 'secondaryIcon' => 'checklist'])
<section class="w-full py-20"><div class="page-container"><x-waggies.cta-primary :cta="$relocationCta" /></div></section>

@endsection
