@extends('layouts.app')

@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Relocation', 'route' => 'services.relocation']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.cover-hero :hero="array_merge($hero, ['eyebrow' => 'IMPORT & EXPORT RELOCATION', 'eyebrowIcon' => 'airport-departure', 'title' => 'Move Your Pet<br/><span class=\"text-secondary italic\">With a Clearer Plan</span>', 'description' => 'Waggies provides custom-quoted import and export coordination for dogs and cats. Airline, airport, veterinary, documentation, crate, and transfer details are reviewed together.', 'actions' => [['label' => 'Submit Booking Request', 'url' => route('book', ['service' => 'relocation']), 'icon' => 'arrow-forward']]])" />
    <div class="page-container -mt-8 relative z-10"><a href="{{ route('relocation.checklist') }}" class="inline-flex min-h-11 items-center gap-2 rounded-full border border-white/30 bg-primary-dark/80 px-4 py-2 text-sm font-semibold text-white hover:bg-primary-dark focus:outline-none focus-visible:ring-2 focus-visible:ring-secondary">Open Relocation Checklist <x-waggies.icon name="checklist" size="18" /></a></div>

    <section class="bg-white py-20"><div class="page-container"><x-waggies.section-heading eyebrow="TWO RELOCATION DIRECTIONS" title="Choose import or export" subtitle="Both directions are request-based, custom-quoted, and manually reviewed before Waggies commits to third-party bookings." /><div class="mt-10 grid gap-6 md:grid-cols-2">@foreach($cards as $card)<x-waggies.service-card :card="$card" />@endforeach</div></div></section>

    <section class="border-t border-primary/5 bg-surface py-20"><div class="page-container"><x-waggies.section-heading eyebrow="WHAT MAY BE INCLUDED" title="A relocation quote is itemized where practical" subtitle="Airport transfers are internal components of an import or export request, not a standalone Waggies service." /><div class="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach(['Airline costs', 'Airport or third-party charges', 'Veterinary and documentation costs', 'Crate or travel equipment', 'Airport transfer costs', 'Waggies coordination fees'] as $item)<div class="rounded-2xl border border-primary/10 bg-white p-5"><x-waggies.icon name="check-circle" variant="filled" size="20" class="text-primary" /><p class="mt-3 text-sm font-semibold text-primary-dark">{{ $item }}</p></div>@endforeach</div></div></section>

    <section class="border-t border-primary/5 bg-primary-dark py-16 text-white"><div class="page-container grid gap-8 lg:grid-cols-2"><div><p class="text-eyebrow text-secondary">MANUAL REVIEW</p><h2 class="mt-2 font-serif text-3xl font-bold text-white">The owner supplies originals. Waggies coordinates the process.</h2><p class="mt-4 max-w-xl text-sm leading-relaxed text-white/70">Share the direction, origin, destination, travel date, pet species, chip status, documentation status, airline and airport details, and pickup or destination notes. We will review feasibility with you.</p></div><div class="grid gap-3 sm:grid-cols-2">@foreach(['Microchip checks or implantation where applicable', 'Facilitation of veterinary steps', 'Airline and airport coordination', 'Pickup and destination coordination'] as $item)<div class="rounded-xl border border-white/10 bg-white/5 p-4 text-sm text-white/80">{{ $item }}</div>@endforeach</div></div></section>

    @if($faqs !== [])<section class="bg-white py-16"><div class="page-container"><x-waggies.section-heading title="Relocation questions" spacing="mb-8" /><x-waggies.faq-accordion :faqs="$faqs" /></div></section>@endif
@endsection
