<div x-data="waggiesChat" x-init="window.addEventListener('scroll', () => showTop = window.scrollY > 400); $watch('chatOpen', open => { if (open) { $nextTick(() => $refs.chatInput?.focus()) } })" class="fixed bottom-20 right-4 z-40 flex flex-col items-end gap-3 sm:bottom-6 sm:right-6 lg:bottom-6">
    <div x-cloak x-show="chatOpen" x-transition class="waggies-chat-panel fixed z-[51] flex flex-col overflow-hidden rounded-2xl border border-primary/10 bg-white shadow-xl" role="dialog" aria-modal="true" aria-label="Waggies AI Assistant chat">
        <div class="flex shrink-0 items-center justify-between bg-primary px-5 py-4 text-white"><div class="flex items-center gap-3"><div class="flex h-8 w-8 items-center justify-center rounded-full bg-white/20"><x-waggies.icon name="assistant" size="18" class="text-white" /></div><div><h3 class="text-sm font-semibold text-white">Waggies AI Assistant</h3><p class="flex items-center gap-1.5 text-xs text-white/70">Typically replies instantly <span class="rounded-full bg-white/10 px-1.5 py-0.5 text-[10px] font-medium text-white/60">Preview</span></p></div></div><button type="button" aria-label="Close chat" class="flex min-h-11 min-w-11 items-center justify-center rounded-lg transition-colors hover:bg-white/10" @click="chatOpen = false"><x-waggies.icon name="close" size="18" class="text-white" /></button></div>
        <div class="flex-1 space-y-4 overflow-y-auto px-4 py-4"><template x-for="(message, index) in messages" :key="index"><div class="flex" :class="message.role === 'user' ? 'justify-end' : 'justify-start'"><div class="max-w-[80%]"><p class="rounded-2xl px-4 py-2.5 text-sm leading-relaxed" :class="message.role === 'bot' ? 'rounded-bl-md bg-surface-purple text-primary-dark' : 'rounded-br-md bg-primary text-white'" x-text="message.text"></p><a x-show="message.link" :href="message.link?.href" @click="chatOpen = false" class="mt-1 inline-block text-xs font-semibold text-primary underline" x-text="message.link?.text"></a></div></div></template></div>
        <form class="flex shrink-0 items-center gap-2 border-t border-primary/5 px-4 py-3 pb-[max(0.75rem,env(safe-area-inset-bottom))]" @submit.prevent="send()"><label class="sr-only" for="chat-input">Chat message</label><input id="chat-input" x-ref="chatInput" x-model="input" type="text" placeholder="Type a message..." class="min-w-0 flex-1 rounded-full border border-primary/10 bg-surface px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"><button type="submit" class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-primary text-white transition-colors hover:bg-primary-dark disabled:cursor-not-allowed disabled:opacity-40" aria-label="Send message" :disabled="!input.trim()"><x-waggies.icon name="send" size="18" class="text-white" /></button></form>
    </div>
    <button type="button" x-show="!chatOpen && showTop" x-transition aria-label="Scroll to top" class="waggies-fab--back-to-top fixed z-50 flex h-11 w-11 items-center justify-center rounded-full bg-primary text-white shadow-lg transition-colors hover:bg-primary-dark" @click="window.scrollTo({ top: 0, behavior: window.matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth' })"><x-waggies.icon name="arrow-up" size="20" class="text-white" /></button>
    <div x-show="!chatOpen" x-transition class="waggies-fab--whatsapp fixed z-50 group"><a href="https://wa.me/2349080811902" target="_blank" rel="noopener noreferrer" class="block flex h-14 w-14 items-center justify-center rounded-full bg-[#25D366] text-white shadow-2xl transition duration-200 hover:scale-110 hover:ring-4 hover:ring-white" aria-label="Chat on WhatsApp"><x-waggies.brand-icon name="whatsapp" size="24" class="text-white" /></a><div class="pointer-events-none absolute bottom-full right-0 mb-2 opacity-0 transition-opacity duration-200 group-hover:opacity-100"><div class="whitespace-nowrap rounded-full bg-primary-dark px-3 py-1.5 text-xs font-semibold text-white shadow-md">Chat on WhatsApp</div></div></div>
    <button type="button" x-show="!chatOpen" x-transition class="waggies-fab--assistant fixed z-50 flex h-14 w-14 items-center justify-center rounded-full bg-primary text-white shadow-2xl transition-colors hover:bg-primary-dark" aria-label="Open Waggies AI Assistant" @click="chatOpen = true"><x-waggies.icon name="assistant" size="24" class="text-white" /></button>
</div>
