@props(['images', 'categories'])

<div x-data="galleryLightbox(@js($images), @js($categories))">
    <div class="flex flex-wrap items-center justify-center gap-2 mb-10">
        <template x-for="category in ['All', ...categories]" :key="category"><button type="button" @click="selectCategory(category)" class="relative px-5 py-2.5 rounded-full text-sm font-semibold transition-colors min-h-[44px]" :class="activeCategory === category ? 'text-white' : 'text-primary-dark/70 hover:text-primary-dark hover:bg-surface-purple/60'"><span x-show="activeCategory === category" class="absolute inset-0 rounded-full bg-primary shadow-sm" x-transition></span><span class="relative z-10" x-text="category"></span></button></template>
    </div>
    <div class="columns-1 sm:columns-2 lg:columns-3 gap-4 [column-fill:balance]">
        <template x-for="(image, index) in images" :key="image.src + '-' + index"><button x-show="isVisible(image)" x-transition.opacity type="button" @click="openAt(index)" class="group relative block w-full mb-4 break-inside-avoid rounded-xl overflow-hidden bg-surface-purple shadow-sm hover:shadow-[0_20px_40px_-15px_rgba(107,44,145,0.4)] transition-shadow cursor-zoom-in" :aria-label="'Open ' + image.alt + ' in lightbox'"><img :src="image.src" :srcset="image.srcset || null" sizes="(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw" :alt="image.alt" loading="lazy" class="w-full object-cover transition-transform duration-500 group-hover:scale-[1.05]" :class="cellAspect(visibleIndex(index))"><div class="absolute inset-x-0 bottom-0 bg-primary-dark/75 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4"><div class="flex items-center gap-2 text-white"><span class="grid place-items-center w-9 h-9 rounded-full bg-white/20 border border-white/40"><x-waggies.icon name="zoom-in" size="20" /></span><div class="flex flex-col leading-tight"><span class="text-[10px] uppercase tracking-wide opacity-80" x-text="image.category"></span><span class="text-sm font-semibold" x-text="image.alt"></span></div></div></div><span class="absolute top-3 left-3 px-2.5 py-1 rounded-full bg-white text-[10px] font-semibold uppercase tracking-wide text-primary-dark" x-text="image.category"></span></button></template>
    </div>
    <div x-show="open && currentImage()" x-cloak x-effect="lockScroll()" class="fixed inset-0 z-layer-lightbox bg-primary-dark/95 flex flex-col" role="dialog" aria-modal="true" :aria-label="'Image lightbox ' + (lightboxIndex + 1) + ' of ' + visibleImages().length" @click.self="closeLightbox()" @pointerdown="pointerStart($event)" @pointerup="pointerEnd($event)" @keydown.escape.window="closeLightbox()" @keydown.arrow-right.window="goNext()" @keydown.arrow-left.window="goPrev()">
        <div class="flex items-center justify-between px-4 sm:px-8 py-4 text-white/80 text-sm"><span class="font-semibold tracking-wide"><span x-text="lightboxIndex + 1"></span> <span class="text-white/40">/</span> <span x-text="visibleImages().length"></span></span><button type="button" @click="closeLightbox()" class="grid place-items-center w-11 h-11 rounded-full bg-white/10 hover:bg-white/20 border border-white/15 text-white transition-[background-color]" aria-label="Close lightbox"><x-waggies.icon name="close" size="20" /></button></div>
        <div class="relative flex-1 flex items-center justify-center px-4 sm:px-20 pb-6"><button type="button" @click.stop="goPrev()" class="absolute top-1/2 -translate-y-1/2 left-2 sm:left-6 grid place-items-center w-12 h-12 sm:w-14 sm:h-14 rounded-full bg-white/10 hover:bg-white/25 border border-white/15 text-white transition-[background-color]" aria-label="Previous image"><x-waggies.icon name="chevron-left" size="24" /></button><template x-if="currentImage()"><figure class="flex flex-col items-center max-w-[90vw] max-h-[80vh]"><img :src="currentImage().src" :srcset="currentImage().srcset || null" :alt="currentImage().alt" class="max-h-[78vh] max-w-full object-contain rounded-lg shadow-[0_30px_80px_-20px_rgba(0,0,0,0.6)]"><figcaption class="mt-4 text-center text-white/85"><span class="text-[11px] uppercase tracking-wider text-primary-light font-semibold" x-text="currentImage().category"></span><span class="mx-2 text-white/30">·</span><span class="text-sm" x-text="currentImage().groupTitle"></span></figcaption></figure></template><button type="button" @click.stop="goNext()" class="absolute top-1/2 -translate-y-1/2 right-2 sm:right-6 grid place-items-center w-12 h-12 sm:w-14 sm:h-14 rounded-full bg-white/10 hover:bg-white/25 border border-white/15 text-white transition-[background-color]" aria-label="Next image"><x-waggies.icon name="chevron-right" size="24" /></button></div>
        <div class="pb-4 text-center text-[11px] text-white/40 sm:hidden">Swipe to navigate · tap outside to close</div>
    </div>
</div>
