@props([
    'name' => 'pets',
    'size' => 20,
    'variant' => 'outlined',
    'class' => '',
])

@php
    $icons = [
        'home' => ['outlined' => 'home.svg', 'filled' => 'home-fill.svg'],
        'services' => ['outlined' => 'category.svg', 'filled' => 'category-fill.svg'],
        'about' => ['outlined' => 'info.svg', 'filled' => 'info-fill.svg'],
        'contact' => ['outlined' => 'contact_support.svg', 'filled' => 'contact_support-fill.svg'],
        'phone' => ['outlined' => 'call.svg', 'filled' => 'call-fill.svg'],
        'call' => ['outlined' => 'call.svg', 'filled' => 'call-fill.svg'],
        'email' => ['outlined' => 'mail.svg', 'filled' => 'mail-fill.svg'],
        'location' => ['outlined' => 'location_on.svg', 'filled' => 'location_on-fill.svg'],
        'hours' => ['outlined' => 'schedule.svg', 'filled' => 'schedule-fill.svg'],
        'calendar' => ['outlined' => 'calendar_month.svg', 'filled' => 'calendar_month-fill.svg'],
        'cake' => ['outlined' => 'cake.svg', 'filled' => 'cake-fill.svg'],
        'pets' => ['outlined' => 'pets.svg', 'filled' => 'pets-fill.svg'],
        'dog' => ['outlined' => 'pets.svg', 'filled' => 'pets-fill.svg'],
        'cat' => ['outlined' => 'pets.svg', 'filled' => 'pets-fill.svg'],
        'exotic-pet' => ['outlined' => 'pets.svg', 'filled' => 'pets-fill.svg'],
        'grooming' => ['outlined' => 'spa.svg', 'filled' => 'spa-fill.svg'],
        'veterinary-care' => ['outlined' => 'medical_services.svg', 'filled' => 'medical_services-fill.svg'],
        'training' => ['outlined' => 'school.svg', 'filled' => 'school-fill.svg'],
        'boarding' => ['outlined' => 'apartment.svg', 'filled' => 'apartment-fill.svg'],
        'relocation' => ['outlined' => 'flight_takeoff.svg', 'filled' => 'flight_takeoff-fill.svg'],
        'airport-arrival' => ['outlined' => 'flight_land.svg', 'filled' => 'flight_land-fill.svg'],
        'airport-departure' => ['outlined' => 'flight_takeoff.svg', 'filled' => 'flight_takeoff-fill.svg'],
        'transport' => ['outlined' => 'local_shipping.svg', 'filled' => 'local_shipping-fill.svg'],
        'checklist' => ['outlined' => 'checklist.svg', 'filled' => 'checklist-fill.svg'],
        'medical' => ['outlined' => 'medical_information.svg', 'filled' => 'medical_information-fill.svg'],
        'vaccination' => ['outlined' => 'vaccines.svg', 'filled' => 'vaccines-fill.svg'],
        'warning' => ['outlined' => 'warning.svg', 'filled' => 'warning-fill.svg'],
        'emergency' => ['outlined' => 'warning.svg', 'filled' => 'warning-fill.svg'],
        'verified' => ['outlined' => 'verified.svg', 'filled' => 'verified-fill.svg'],
        'search' => ['outlined' => 'search.svg', 'filled' => 'search-fill.svg'],
        'menu' => ['outlined' => 'menu.svg', 'filled' => 'menu-fill.svg'],
        'close' => ['outlined' => 'close.svg', 'filled' => 'close-fill.svg'],
        'arrow-forward' => ['outlined' => 'arrow_forward.svg', 'filled' => 'arrow_forward-fill.svg'],
        'arrow-back' => ['outlined' => 'arrow_back.svg', 'filled' => 'arrow_back-fill.svg'],
        'arrow-up' => ['outlined' => 'arrow_upward.svg', 'filled' => 'arrow_upward-fill.svg'],
        'progress' => ['outlined' => 'trending_up.svg', 'filled' => 'trending_up-fill.svg'],
        'refresh' => ['outlined' => 'refresh.svg', 'filled' => 'refresh-fill.svg'],
        'open-in-new' => ['outlined' => 'open_in_new.svg', 'filled' => 'open_in_new-fill.svg'],
        'chevron-down' => ['outlined' => 'keyboard_arrow_down.svg', 'filled' => 'keyboard_arrow_down-fill.svg'],
        'chevron-up' => ['outlined' => 'keyboard_arrow_up.svg', 'filled' => 'keyboard_arrow_up-fill.svg'],
        'chevron-right' => ['outlined' => 'keyboard_arrow_right.svg', 'filled' => 'keyboard_arrow_right-fill.svg'],
        'chevron-left' => ['outlined' => 'keyboard_arrow_left.svg', 'filled' => 'keyboard_arrow_left-fill.svg'],
        'check' => ['outlined' => 'check.svg', 'filled' => 'check-fill.svg'],
        'info' => ['outlined' => 'info.svg', 'filled' => 'info-fill.svg'],
        'check-circle' => ['outlined' => 'check_circle.svg', 'filled' => 'check_circle-fill.svg'],
        'remove' => ['outlined' => 'remove.svg', 'filled' => 'remove-fill.svg'],
        'add' => ['outlined' => 'add.svg', 'filled' => 'add-fill.svg'],
        'delete' => ['outlined' => 'delete.svg', 'filled' => 'delete-fill.svg'],
        'print' => ['outlined' => 'print.svg', 'filled' => 'print-fill.svg'],
        'shopping-cart' => ['outlined' => 'shopping_cart.svg', 'filled' => 'shopping_cart-fill.svg'],
        'add-to-cart' => ['outlined' => 'add_shopping_cart.svg', 'filled' => 'add_shopping_cart-fill.svg'],
        'shopping-bag' => ['outlined' => 'shopping_bag.svg', 'filled' => 'shopping_bag-fill.svg'],
        'cart' => ['outlined' => 'shopping_cart.svg', 'filled' => 'shopping_cart-fill.svg'],
        'filter' => ['outlined' => 'filter_alt.svg', 'filled' => 'filter_alt-fill.svg'],
        'help' => ['outlined' => 'help.svg', 'filled' => 'help-fill.svg'],
        'share' => ['outlined' => 'share.svg', 'filled' => 'share-fill.svg'],
        'favorite' => ['outlined' => 'favorite.svg', 'filled' => 'favorite-fill.svg'],
        'team' => ['outlined' => 'groups.svg', 'filled' => 'groups-fill.svg'],
        'community' => ['outlined' => 'diversity_3.svg', 'filled' => 'diversity_3-fill.svg'],
        'team-member' => ['outlined' => 'person.svg', 'filled' => 'person-fill.svg'],
        'gift' => ['outlined' => 'redeem.svg', 'filled' => 'redeem-fill.svg'],
        'achievement' => ['outlined' => 'workspace_premium.svg', 'filled' => 'workspace_premium-fill.svg'],
        'career' => ['outlined' => 'business_center.svg', 'filled' => 'business_center-fill.svg'],
        'partnership' => ['outlined' => 'handshake.svg', 'filled' => 'handshake-fill.svg'],
        'guide' => ['outlined' => 'menu_book.svg', 'filled' => 'menu_book-fill.svg'],
        'knowledge-base' => ['outlined' => 'book.svg', 'filled' => 'book-fill.svg'],
        'calculator' => ['outlined' => 'calculate.svg', 'filled' => 'calculate-fill.svg'],
        'medication' => ['outlined' => 'medication.svg', 'filled' => 'medication-fill.svg'],
        'nutrition' => ['outlined' => 'restaurant.svg', 'filled' => 'restaurant-fill.svg'],
        'water' => ['outlined' => 'water_drop.svg', 'filled' => 'water_drop-fill.svg'],
        'supplies' => ['outlined' => 'inventory_2.svg', 'filled' => 'inventory_2-fill.svg'],
        'microchip' => ['outlined' => 'qr_code_scanner.svg', 'filled' => 'qr_code_scanner-fill.svg'],
        'climate' => ['outlined' => 'thermostat.svg', 'filled' => 'thermostat-fill.svg'],
        'energy' => ['outlined' => 'bolt.svg', 'filled' => 'bolt-fill.svg'],
        'privacy' => ['outlined' => 'do_not_disturb_on.svg', 'filled' => 'do_not_disturb_on-fill.svg'],
        'parasite' => ['outlined' => 'pest_control.svg', 'filled' => 'pest_control-fill.svg'],
        'behavior' => ['outlined' => 'psychology.svg', 'filled' => 'psychology-fill.svg'],
        'exercise' => ['outlined' => 'directions_walk.svg', 'filled' => 'directions_walk-fill.svg'],
        'air' => ['outlined' => 'air.svg', 'filled' => 'air-fill.svg'],
        'hearing' => ['outlined' => 'hearing.svg', 'filled' => 'hearing-fill.svg'],
        'mouth' => ['outlined' => 'sentiment_satisfied.svg', 'filled' => 'sentiment_satisfied-fill.svg'],
        'document' => ['outlined' => 'description.svg', 'filled' => 'description-fill.svg'],
        'coordinator' => ['outlined' => 'support_agent.svg', 'filled' => 'support_agent-fill.svg'],
        'assistant' => ['outlined' => 'smart_toy.svg', 'filled' => 'smart_toy-fill.svg'],
        'chat' => ['outlined' => 'chat.svg', 'filled' => 'chat-fill.svg'],
        'safety' => ['outlined' => 'health_and_safety.svg', 'filled' => 'health_and_safety-fill.svg'],
        'photo' => ['outlined' => 'photo_camera.svg', 'filled' => 'photo_camera-fill.svg'],
        'quotes' => ['outlined' => 'format_quote.svg', 'filled' => 'format_quote-fill.svg'],
        'star' => ['outlined' => 'star.svg', 'filled' => 'star-fill.svg'],
        'reviews' => ['outlined' => 'reviews.svg', 'filled' => 'reviews-fill.svg'],
        'loyalty' => ['outlined' => 'card_membership.svg', 'filled' => 'card_membership-fill.svg'],
        'global' => ['outlined' => 'public.svg', 'filled' => 'public-fill.svg'],
        'values' => ['outlined' => 'diamond.svg', 'filled' => 'diamond-fill.svg'],
        'process' => ['outlined' => 'sync.svg', 'filled' => 'sync-fill.svg'],
        'visibility' => ['outlined' => 'visibility.svg', 'filled' => 'visibility-fill.svg'],
        'security' => ['outlined' => 'shield.svg', 'filled' => 'shield-fill.svg'],
        'public' => ['outlined' => 'public.svg', 'filled' => 'public-fill.svg'],
        'payments' => ['outlined' => 'payments.svg', 'filled' => 'payments-fill.svg'],
        'send' => ['outlined' => 'send.svg', 'filled' => 'send-fill.svg'],
        'edit' => ['outlined' => 'edit.svg', 'filled' => 'edit-fill.svg'],
        'error' => ['outlined' => 'error.svg', 'filled' => 'error-fill.svg'],
    ];
    $icon = $icons[$name] ?? $icons['pets'];
    $file = $icon[$variant] ?? $icon['outlined'];
@endphp

<span aria-hidden="true" class="inline-block shrink-0 bg-current {{ $class }}" style="width: {{ $size }}px; height: {{ $size }}px; mask: url('{{ asset('icons/material-symbols/outlined/'.$file) }}') center / contain no-repeat; -webkit-mask: url('{{ asset('icons/material-symbols/outlined/'.$file) }}') center / contain no-repeat;"></span>
