@props(['page', 'faqs' => []])

<div class="bg-white py-12"><div class="mx-auto max-w-3xl px-4 text-center md:px-10 lg:px-12"><p class="text-lg leading-relaxed text-primary-dark/70">{{ $page['description'] }}</p></div></div>

<section class="bg-white py-20"><div class="page-container"><x-waggies.section-heading title="What you can request" subtitle="Choose the care request that best describes what your pet needs. Staff review the details before confirmation." spacing="mb-12" /><ul class="grid gap-x-12 md:grid-cols-2">@foreach($page['features'] as $index => $feature)<li class="flex gap-4 border-t border-primary-dark/15 py-6 {{ $index === 0 ? 'rounded-2xl border border-primary/20 bg-surface-purple/55 px-6 py-7 md:col-span-2 md:mb-2' : '' }}"><span aria-hidden="true" class="font-serif text-sm font-bold tracking-[0.18em] text-primary/70">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span><p class="max-w-xl font-medium leading-relaxed text-primary-dark/80">{{ $feature }}</p></li>@endforeach</ul></div></section>

<section class="bg-surface-purple/40 py-20"><div class="page-container"><x-waggies.section-heading title="How veterinary review works" subtitle="A request starts the clinical conversation; it is not an online checkout or confirmed appointment." spacing="mb-10" /><div class="grid gap-4 md:grid-cols-2">@foreach($page['benefits'] as $benefit)<div class="flex items-start gap-4 rounded-2xl border border-primary/10 bg-white p-5"><x-waggies.icon name="check-circle" variant="filled" size="20" class="mt-0.5 shrink-0 text-primary" /><p class="text-sm leading-relaxed text-primary-dark/75">{{ $benefit }}</p></div>@endforeach</div></div></section>

<section class="bg-white py-20"><div class="page-container"><x-waggies.section-heading title="Veterinary request options" subtitle="Indicative consultation amounts are not final quotes. Vaccination and microchip requests remain review-only until staff confirm the details." spacing="mb-10" /><div class="grid gap-5 md:grid-cols-2">@foreach($page['options'] as $option)<div class="rounded-2xl border border-primary/10 bg-surface p-6">@if($option['category'])<p class="text-eyebrow text-primary">{{ $option['category'] }}</p>@endif<div class="mt-1 flex items-start justify-between gap-4"><h3 class="font-serif text-xl font-bold text-primary-dark">{{ $option['label'] }}</h3><span class="shrink-0 text-sm font-semibold text-primary">{{ $option['price'] }}</span></div>@if($option['description'])<p class="mt-3 text-sm leading-relaxed text-primary-dark/65">{{ $option['description'] }}</p>@endif</div>@endforeach</div></div></section>

@if($faqs !== [])<section class="bg-surface py-16"><div class="page-container"><x-waggies.section-heading title="Veterinary care questions" spacing="mb-8" /><x-waggies.faq-accordion :faqs="$faqs" /></div></section>@endif

<section class="bg-primary-dark py-16"><div class="page-container flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><h2 class="font-serif text-2xl font-bold text-white md:text-3xl">Ready to request veterinary care?</h2><p class="mt-2 text-sm text-white/70">Send the pet and clinical context for staff review.</p></div><x-waggies.button href="{{ route($page['ctaRoute'], $page['ctaParams'] ?? []) }}" class="bg-secondary! text-primary-dark!">{{ $page['ctaText'] }} <x-waggies.icon name="arrow-forward" size="16" /></x-waggies.button></div></section>
