@props(['page', 'faqs' => []])

@if(!empty($page['descriptionBlock']))<div class="bg-white py-12"><div class="mx-auto max-w-3xl px-4 text-center md:px-10 lg:px-12"><p class="text-lg leading-relaxed text-primary-dark/70">{{ $page['descriptionBlock'] }}</p></div></div>@endif

<section class="bg-white py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><h2 class="mb-4 text-center font-serif text-3xl font-bold text-primary-dark md:text-4xl">What&apos;s Included</h2><p class="mx-auto mb-12 max-w-2xl text-center text-primary-dark/60">Every service is delivered with care, professionalism, and attention to detail.</p><div class="grid grid-cols-1 gap-x-12 md:grid-cols-2">
    @foreach($page['features'] as $index => $feature)<div class="group relative flex gap-4 border-t border-primary-dark/15 py-6 {{ $index === 0 ? 'rounded-2xl border border-primary/20 bg-surface-purple/55 px-6 py-7 md:col-span-2 md:mb-2' : '' }}"><span aria-hidden="true" class="font-serif text-sm font-bold tracking-[0.18em] text-primary/70">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span><p class="max-w-xl font-medium leading-relaxed text-primary-dark/80 transition-transform duration-300 ease-out group-hover:translate-x-1">{{ $feature }}</p></div>@endforeach
</div></div></section>

<section class="bg-surface-purple/40 py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><h2 class="mb-4 text-center font-serif text-3xl font-bold text-primary-dark md:text-4xl">Why Choose Us</h2><p class="mx-auto mb-14 max-w-2xl text-center text-primary-dark/60">Trusted by hundreds of pet owners across Abuja.</p><div class="mx-auto grid max-w-5xl grid-cols-1 gap-x-16 gap-y-10 md:grid-cols-2">
    @foreach($page['benefits'] as $index => $benefit)<div class="flex items-start gap-5"><div class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white shadow-[inset_0_0_0_1px_oklch(0.332_0.155_305/0.14)]"><x-waggies.icon name="{{ $index % 2 === 0 ? 'verified' : 'favorite' }}" size="20" class="text-primary" /></div><p class="pt-1.5 text-[1.0625rem] leading-relaxed text-primary-dark/80">{{ $benefit }}</p></div>@endforeach
</div></div></section>

<section class="bg-white py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><h2 class="mb-4 text-center font-serif text-3xl font-bold text-primary-dark md:text-4xl">Packages &amp; Pricing</h2><p class="mx-auto mb-12 max-w-2xl text-center text-primary-dark/60">Choose the package that best suits your pet&apos;s needs.</p><div class="grid grid-cols-1 gap-8 md:grid-cols-3">
    @foreach($page['packages'] as $package)<div class="relative flex flex-col gap-4 rounded-2xl border {{ !empty($package['popular']) ? 'border-primary shadow-sm' : 'border-surface-purple' }} bg-white p-8 transition-shadow hover:shadow-soft">@if(!empty($package['popular']))<span class="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1 text-xs font-bold uppercase tracking-wider text-white">Most Popular</span>@endif<h3 class="font-serif text-xl font-bold text-primary-dark">{{ $package['name'] }}</h3><p class="text-xs font-medium uppercase tracking-wider text-primary-dark/50">Final availability confirmed on WhatsApp</p><p class="font-serif text-3xl font-bold text-primary">Provisional route estimate</p><ul class="mt-2 flex flex-col gap-2"><li class="flex items-start gap-2 text-sm text-primary-dark/70"><x-waggies.icon name="check-circle" variant="filled" size="16" class="mt-0.5 shrink-0 text-primary" />Route-specific provisional estimate</li><li class="flex items-start gap-2 text-sm text-primary-dark/70"><x-waggies.icon name="check-circle" variant="filled" size="16" class="mt-0.5 shrink-0 text-primary" />Final charges confirmed on WhatsApp</li></ul><a href="{{ route($page['ctaRoute'], $page['ctaParams'] ?? []) }}" class="w-cta w-cta--{{ !empty($package['popular']) ? 'primary' : 'secondary' }} mt-auto w-full px-6 py-3 text-sm leading-5">{{ $page['ctaText'] }} <x-waggies.icon name="arrow-forward" size="16" /></a></div>@endforeach
</div></div></section>

@if(count($faqs))<section class="bg-surface-purple/40 py-16"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><h2 class="mb-8 text-center font-serif text-3xl font-bold text-primary-dark md:text-4xl">Frequently Asked Questions</h2><x-waggies.faq-accordion :faqs="$faqs" /><p class="mt-6 text-center text-sm text-primary-dark/50">More questions? <a href="{{ route('faq') }}" class="font-medium text-primary hover:underline">View all FAQs</a> or <a href="{{ route('contact') }}" class="font-medium text-primary hover:underline">contact us</a>.</p></div></section>@endif

<section class="bg-primary-dark py-16"><div class="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 px-4 md:flex-row md:px-10 lg:px-12"><div><h2 class="mb-2 font-serif text-2xl font-bold text-white md:text-3xl">Ready to Get Started?</h2><p class="text-white/70">Book your {{ strtolower($page['metaTitle']) }} appointment today and give your pet the care they deserve.</p></div><a href="{{ route($page['ctaRoute'], $page['ctaParams'] ?? []) }}" class="w-cta w-cta--primary shrink-0 !bg-secondary !text-primary-dark hover:!bg-secondary-hover">{{ $page['ctaText'] }} <x-waggies.icon name="arrow-forward" size="16" /></a></div></section>
