@extends('layouts.app')
@section('content')
<x-waggies.breadcrumb-strip class="border-b border-primary/5 bg-white" :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Boarding', 'route' => 'services.boarding']]" />
<x-waggies.cover-hero :hero="$page['hero']" />
<section class="bg-surface py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><x-waggies.section-heading eyebrow="Species-Dedicated Suites" title="Choose the Right Stay<br/>for Your Pet" subtitle="We offer tailored boarding for dogs, cats, and exotic animals - each in a dedicated, species-appropriate environment."/><div class="grid grid-cols-1 gap-6 sm:grid-cols-3">@foreach($page['cards'] as $card)<x-waggies.service-card :card="$card" />@endforeach</div></div></section>
<section class="border-y border-white/10 bg-primary-dark py-20 text-white"><div class="mx-auto grid max-w-7xl items-center gap-12 px-4 md:px-10 lg:grid-cols-12 lg:px-12"><div class="space-y-6 lg:col-span-5"><span class="text-label block text-secondary">WHAT'S INCLUDED IN EVERY STAY</span><h2 class="text-h2 leading-tight text-white">Everything Covered,<br/><span class="text-secondary italic">Every Single Day</span></h2><p class="text-base leading-relaxed text-white/75">Every boarding stay includes premium amenities, orthopedic bedding, 24/7 supervision, and daily photo updates as standard - no hidden charges.</p><div class="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><x-waggies.icon name="verified" variant="filled" size="32" class="shrink-0 text-secondary"/><p class="text-xs leading-snug text-white/80">Licensed by PCSA with an on-site veterinarian present every day for maximum safety.</p></div></div><div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:col-span-7">@foreach($page['included'] as $feature)<div class="flex items-start gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><div class="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white/10 text-secondary"><x-waggies.icon name="{{ $feature['icon'] }}" class="text-xl"/></div><div><h3 class="mb-1 text-base font-bold text-white">{{ $feature['title'] }}</h3><p class="text-xs leading-relaxed text-white/65">{{ $feature['desc'] }}</p></div></div>@endforeach</div></div></section>
<x-waggies.proof-band variant="boarding" />
<section class="bg-surface py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><x-waggies.section-heading eyebrow="FREQUENT QUESTIONS" title="Before You Book Boarding" subtitle="Quick answers to help you prepare your pet for their upcoming stay with peace of mind." spacing="mb-14" /><x-waggies.faq-accordion :faqs="$faqs" /></div></section>
<section class="w-full py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><div class="w-full rounded-2xl bg-primary-dark"><div class="mx-auto flex max-w-5xl flex-col gap-10 px-4 py-12 md:flex-row md:items-center md:justify-between md:px-10 md:py-16 lg:px-12"><div class="max-w-xl text-center md:text-left"><h2 class="font-serif text-3xl font-bold leading-tight text-white md:text-4xl">Secure Your Pet’s Stay<br/><span class="text-secondary italic">While You're Away</span></h2><p class="mt-5 max-w-md text-base leading-relaxed text-white/65">Reserve your pet’s suite today and enjoy complete peace of mind with daily updates, expert care, and 24/7 supervision.</p></div><div class="flex flex-wrap justify-center gap-3 md:justify-end"><a href="{{ route('contact', ['intent' => 'service', 'service' => 'boarding']) }}" class="w-cta w-cta--primary !bg-secondary !text-primary-dark">Request Boarding <x-waggies.icon name="arrow-forward" size="16"/></a><a href="{{ route('services.pricing', ['service' => 'boarding']) }}" class="w-cta w-cta--secondary border-white/30 bg-transparent text-white hover:bg-white/10"><x-waggies.icon name="calculator" size="16"/>Get Estimate</a></div></div></div></div></section>
@endsection
