@extends('layouts.app')
@section('content')
<x-waggies.breadcrumb-strip class="border-b border-primary/5 bg-white" :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Boarding', 'route' => 'services.boarding']]" />
<x-waggies.cover-hero :hero="$page['hero']" />
<section class="bg-surface py-20"><div class="page-container"><x-waggies.section-heading eyebrow="Dog & Cat Boarding" title="Choose the Right Stay<br/>for Your Pet" subtitle="We offer boarding for dogs and cats, with each pet receiving an individual enclosure and care reviewed before confirmation."/><div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-6">@foreach($page['cards'] as $index => $card)<div class="h-full lg:col-span-2 {{ $index === 0 ? 'lg:col-start-2' : 'lg:col-start-4' }}"><x-waggies.service-card :card="$card" /></div>@endforeach</div></div></section>
<section class="border-y border-white/10 bg-primary-dark py-20 text-white"><div class="page-container grid items-center gap-12 lg:grid-cols-12"><div class="space-y-6 lg:col-span-5"><span class="text-label block text-secondary">WHAT'S INCLUDED IN EVERY STAY</span><h2 class="text-h2 leading-tight text-white">Everything Covered,<br/><span class="text-secondary italic">Every Single Stay</span></h2><p class="text-base leading-relaxed text-white/75">Every boarding stay includes an individual enclosure, water, owner-supplied food and feeding instructions, routine cleaning, basic welfare checks, and a light bath or wash for boarded dogs before pickup where safe and appropriate.</p><div class="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><x-waggies.icon name="verified" variant="filled" size="32" class="shrink-0 text-secondary"/><p class="text-xs leading-snug text-white/80">Availability, special-care needs, and final pricing are confirmed manually.</p></div></div><div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:col-span-7">@foreach($page['included'] as $feature)<div class="flex items-start gap-4 rounded-2xl border border-white/10 bg-white/5 p-5"><div class="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white/10 text-secondary"><x-waggies.icon name="{{ $feature['icon'] }}" class="text-xl"/></div><div><h3 class="mb-1 text-base font-bold text-white">{{ $feature['title'] }}</h3><p class="text-xs leading-relaxed text-white/65">{{ $feature['desc'] }}</p></div></div>@endforeach</div></div></section>
<x-waggies.proof-band variant="boarding" />
<section class="bg-surface py-20"><div class="page-container"><x-waggies.section-heading eyebrow="FREQUENT QUESTIONS" title="Before You Book Boarding" subtitle="Quick answers to help you prepare your pet for their upcoming stay with peace of mind." spacing="mb-14" /><x-waggies.faq-accordion :faqs="$faqs" /></div></section>
@php($boardingCta = ['heading' => 'Request Your Pet’s Stay', 'headingAccent' => 'While You\'re Away', 'body' => 'Send your preferred dates and pet details. Waggies will review availability, care needs, and final pricing with you.', 'primaryLabel' => 'Submit Boarding Request', 'primaryRoute' => 'book', 'primaryParams' => ['service' => 'boarding']])
<section class="w-full py-20"><div class="page-container"><x-waggies.cta-split :cta="$boardingCta" /></div></section>
@endsection
