@extends('layouts.app')

@section('content')
@php
    $serviceKey = 'boarding-'.$species;
    $dailyBadges = match ($species) {
        'dogs' => [['badge' => 'Settling', 'bg' => 'bg-purple-50 text-primary-dark border-purple-200'], ['badge' => 'Nutrition', 'bg' => 'bg-emerald-50 text-emerald-800 border-emerald-200'], ['badge' => 'Cleaning', 'bg' => 'bg-amber-50 text-amber-800 border-amber-200'], ['badge' => 'Welfare Check', 'bg' => 'bg-blue-50 text-blue-800 border-blue-200'], ['badge' => 'Pickup Prep', 'bg' => 'bg-indigo-50 text-indigo-800 border-indigo-200']],
        'cats' => [['badge' => 'Settling', 'bg' => 'bg-purple-50 text-primary-dark border-purple-200'], ['badge' => 'Nutrition', 'bg' => 'bg-amber-50 text-amber-800 border-amber-200'], ['badge' => 'Cleaning', 'bg' => 'bg-emerald-50 text-emerald-800 border-emerald-200'], ['badge' => 'Welfare Check', 'bg' => 'bg-blue-50 text-blue-800 border-blue-200'], ['badge' => 'Evening Care', 'bg' => 'bg-indigo-50 text-indigo-800 border-indigo-200']],
    };
    $dailySurface = $species === 'cats' ? 'bg-white' : 'bg-surface-purple/60';
    $safetyDark = $species === 'dogs';
    $shareTitle = ['dogs' => 'Dog Boarding - Waggies', 'cats' => 'Cat Boarding - Waggies'][$species];
    $shareDescription = $page['description'];
    $dailyHeadingId = $species === 'dogs' ? 'dog-daily-heading' : 'cat-daily-heading';
    $siblings = collect([
        ['key' => 'dogs', 'title' => 'Dog Boarding', 'desc' => 'Individual enclosures, routine care, and manual review.', 'icon' => 'pets'],
        ['key' => 'cats', 'title' => 'Cat Boarding', 'desc' => 'Calm individual enclosures with routine care and manual review.', 'icon' => 'pets'],
    ])->map(fn (array $sibling): array => $sibling + ['image' => "/media/services/boarding/{$species}/related-{$sibling['key']}.jpg"])->all();
@endphp

<x-waggies.breadcrumb-strip class="border-b border-primary/5 bg-white" :items="[['label' => 'Services', 'route' => 'services.index'], ['label' => 'Boarding', 'route' => 'services.boarding'], ['label' => $page['hero']['eyebrow'], 'route' => 'services.boarding.species', 'params' => ['species' => $species]]]" />
<x-waggies.cover-hero :hero="$page['hero']" size="compact" />
<div class="relative z-30 -mt-8 -mb-8 mx-4 max-w-[1200px] rounded-2xl border border-surface-purple bg-white shadow-soft sm:mx-10 lg:mx-auto"><div class="grid grid-cols-2 gap-8 px-6 py-8 md:grid-cols-4 md:divide-x md:divide-primary/10 md:px-10">@foreach($page['stats'] as $stat)<div class="flex flex-col items-center text-center"><span class="mb-1 font-serif text-4xl font-bold text-primary">{{ $stat['value'] }}</span><span class="text-xs font-semibold uppercase tracking-widest text-primary-dark/50">{{ $stat['label'] }}</span></div>@endforeach</div></div>

@if($species === 'dogs')
<section class="border-b border-primary/10 bg-surface-purple/40 py-12"><div class="page-container"><div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach($page['activityHighlights'] as $highlight)<div class="w-card flex items-center gap-4 border border-primary/10 p-5"><div class="flex size-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><x-waggies.icon name="{{ $highlight['icon'] }}" size="24" /></div><div><h4 class="font-serif text-base font-bold text-primary-dark">{{ $highlight['title'] }}</h4><p class="text-xs text-primary-dark/65">{{ $highlight['desc'] }}</p></div></div>@endforeach</div></div></section>
@elseif($species === 'cats')
<section class="border-b border-primary/10 bg-surface-purple/50 py-12"><div class="page-container"><div class="flex flex-col items-center justify-between gap-6 rounded-2xl border border-primary/15 bg-white p-6 shadow-soft md:flex-row md:p-8"><div class="flex max-w-2xl items-start gap-4"><div class="mt-1 flex size-12 shrink-0 items-center justify-center rounded-2xl bg-primary/10 text-primary"><x-waggies.icon name="verified" size="26" variant="filled" /></div><div><span class="mb-1 block text-xs font-bold uppercase tracking-wider text-primary">{{ $page['sanctuary']['eyebrow'] }}</span><h3 class="mb-1 font-serif text-xl font-bold text-primary-dark md:text-2xl">{{ $page['sanctuary']['title'] }}</h3><p class="text-sm leading-relaxed text-primary-dark/70">{{ $page['sanctuary']['body'] }}</p></div></div><div class="flex shrink-0 flex-wrap gap-2">@foreach($page['sanctuary']['badges'] as $badge)<span class="inline-flex items-center gap-1.5 rounded-full border border-primary/10 bg-surface-purple px-3 py-1.5 text-xs font-semibold text-primary"><x-waggies.icon name="{{ $badge['icon'] }}" size="14" />{{ $badge['label'] }}</span>@endforeach</div></div></div></section>
@endif

<section id="boarding-options" class="scroll-mt-24 border-y border-primary/5 bg-surface py-20"><div class="page-container"><x-waggies.section-heading :eyebrow="$page['pricingHeading']['eyebrow']" :title="$page['pricingHeading']['title']" :subtitle="$page['pricingHeading']['subtitle']" /><div class="mx-auto mt-10 grid max-w-6xl grid-cols-1 items-stretch gap-6 md:grid-cols-2 lg:gap-8"><x-waggies.card hover class="relative flex h-full flex-col border-2 border-primary p-8"><p class="mb-3 text-xs font-bold uppercase tracking-widest text-primary/60">{{ $species === 'dogs' ? 'Dog size guidance' : 'Cat boarding' }}</p>@if($species === 'dogs')<div class="space-y-4">@foreach($pricing as $key => $rate)<div class="flex items-start justify-between gap-4 border-b border-primary/10 pb-3 last:border-0"><div><p class="font-semibold text-primary-dark">{{ $rate['booking_label'] ?? $rate['label'] }}</p><p class="mt-1 text-xs text-primary-dark/60">{{ $rate['guidance'] ?? '' }}</p></div><span class="shrink-0 text-sm font-semibold text-primary-dark">{{ ! empty($rate['manual_review']) ? 'Staff review' : '₦'.number_format((int) $rate['amount']).'–₦'.number_format((int) ($rate['max_amount'] ?? $rate['amount'])) }} / night</span></div>@endforeach</div>@else<p class="font-serif text-3xl font-bold text-primary">Quote required</p><p class="mt-3 text-sm leading-relaxed text-primary-dark/65">Cats use one nightly boarding rate rather than packages or tiers. Waggies confirms the current rate during review.</p>@endif<x-waggies.button href="{{ route('book', ['service' => 'boarding', 'variant' => $species]) }}" class="mt-8 w-full justify-center">Submit Booking Request <x-waggies.icon name="arrow-forward" size="16" /></x-waggies.button></x-waggies.card></div><p class="mt-8 text-center text-sm text-primary-dark/60">Need a longer stay or special care? <a href="{{ route('contact') }}" class="font-bold text-primary hover:underline">Contact us</a>. Final availability and pricing are confirmed manually.</p></div></section>

<section class="bg-white py-20"><div class="page-container"><x-waggies.section-heading :eyebrow="$page['featuresHeading']['eyebrow']" :title="$page['featuresHeading']['title']" :subtitle="$page['featuresHeading']['subtitle']" /><x-waggies.service-feature-grid :features="$page['features']" /></div></section>

@if($species === 'cats')<section class="border-t border-primary/5 bg-surface-purple/40 py-20"><div class="page-container"><div class="grid items-center gap-12 lg:grid-cols-12"><div class="lg:col-span-7"><span class="text-eyebrow mb-2 block">{{ $page['feline']['eyebrow'] }}</span><h2 class="mb-4 font-serif text-3xl font-bold leading-tight text-primary-dark md:text-4xl">{{ $page['feline']['title'] }}</h2><p class="mb-8 max-w-prose text-base leading-relaxed text-primary-dark/70">{{ $page['feline']['body'] }}</p><div class="mb-8 space-y-4">@foreach($page['feline']['bullets'] as $bullet)<div class="w-card flex items-start gap-3.5 rounded-xl border border-primary/10 bg-white p-4"><x-waggies.icon name="check-circle" size="20" variant="filled" class="mt-0.5 shrink-0 text-primary" /><span class="text-sm text-primary-dark/85"><strong class="font-bold text-primary-dark">{{ $bullet['bold'] }}</strong> {{ $bullet['text'] }}</span></div>@endforeach</div></div><div class="relative aspect-4/3 w-full overflow-hidden rounded-3xl border border-primary/10 shadow-soft lg:col-span-5"><img src="{{ $page['feline']['image'] }}" alt="{{ $page['feline']['imageAlt'] }}" class="h-full w-full object-cover" loading="lazy" /></div></div></div></section>@endif

<section aria-labelledby="{{ $dailyHeadingId }}" class="{{ $dailySurface }} w-full border-t border-primary/5 py-20"><div class="page-container"><div class="flex flex-col items-center gap-12 lg:flex-row"><div class="flex-1 space-y-8"><div><span class="text-eyebrow mb-2 block">{{ $species === 'cats' ? 'LOW-STRESS DAILY ROUTINE' : 'STRUCTURED CARE SCHEDULE' }}</span><h2 id="{{ $dailyHeadingId }}" class="mb-3 font-serif text-3xl font-bold leading-tight text-primary-dark md:text-4xl">{{ $page['daily']['heading'] }}</h2><p class="max-w-prose text-base leading-relaxed text-primary-dark/70">{{ $page['daily']['subtitle'] }}</p></div><ol class="{{ $species === 'dogs' ? 'space-y-6' : 'space-y-4' }}" aria-label="Daily schedule">@foreach($page['daily']['steps'] as $i => $step)@php($tag = $dailyBadges[$i % count($dailyBadges)])<li class="w-card flex flex-col justify-between gap-4 rounded-2xl border border-primary/10 {{ $species === 'cats' ? 'bg-surface-purple/30' : 'bg-white' }} p-5 {{ $species === 'cats' ? '' : 'transition-shadow hover:shadow-soft' }} sm:flex-row sm:items-center"><div class="flex items-start gap-4"><div class="mt-0.5 flex size-10 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"><x-waggies.icon name="{{ $step['icon'] }}" size="18" /></div><div><h3 class="font-serif text-base font-bold text-primary-dark">{{ $step['title'] }}</h3><p class="mt-1 text-sm leading-relaxed text-primary-dark/65">{{ $step['description'] }}</p></div></div><span class="inline-flex shrink-0 self-start items-center rounded-full border px-3 py-1 text-xs font-semibold {{ $tag['bg'] }} sm:self-center">{{ $tag['badge'] }}</span></li>@endforeach</ol></div><div class="w-full flex-1" aria-hidden="true"><div class="grid grid-cols-2 gap-4"><div class="space-y-4 pt-6"><img src="{{ $page['daily']['images'][0] }}" alt="" class="h-48 w-full rounded-2xl border border-primary/10 object-cover shadow-soft" loading="lazy" /><img src="{{ $page['daily']['images'][1] }}" alt="" class="h-64 w-full rounded-2xl border border-primary/10 object-cover shadow-soft" loading="lazy" /></div><div class="space-y-4"><img src="{{ $page['daily']['images'][2] }}" alt="" class="h-64 w-full rounded-2xl border border-primary/10 object-cover shadow-soft" loading="lazy" /><img src="{{ $page['daily']['images'][3] }}" alt="" class="h-48 w-full rounded-2xl border border-primary/10 object-cover shadow-soft" loading="lazy" /></div></div></div></div></div></section>


<section class="w-full border-t border-primary/5 py-20 {{ $safetyDark ? 'bg-white' : 'bg-surface' }}"><div class="page-container"><div class="relative overflow-hidden rounded-3xl {{ $safetyDark ? 'bg-primary-dark text-white shadow-md' : 'border border-primary/10 bg-white text-primary-dark shadow-soft' }} p-8 md:p-12">@if($safetyDark)<div class="pointer-events-none absolute -bottom-12 -right-12 text-white opacity-10"><x-waggies.icon name="verified" size="260" variant="filled" /></div>@endif<div class="{{ $safetyDark ? 'relative z-10' : '' }} max-w-3xl">@if($safetyDark)<div class="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3.5 py-1 text-xs font-bold uppercase tracking-wider text-secondary"><x-waggies.icon name="verified" size="16" variant="filled" />{{ $page['safety']['title'] }}</div>@else<span class="text-eyebrow mb-2 block">{{ $species === 'cats' ? 'LOW-STRESS COMPLIANCE' : 'DOG SAFETY & HANDLING' }}</span>@endif<h2 class="mb-4 font-serif text-2xl font-bold leading-tight {{ $safetyDark ? 'text-white' : 'text-primary-dark' }} md:text-3xl">{{ $species === 'dogs' ? 'Active Supervision & Safety Protocols' : $page['safety']['title'] }}</h2><p class="mb-8 text-sm leading-relaxed {{ $safetyDark ? 'text-white/80' : 'text-primary-dark/70' }} md:text-base">{{ $page['safety']['intro'] }}</p><div class="mb-8 grid gap-4 sm:grid-cols-2">@foreach($page['safety']['bullets'] as $bullet)<div class="flex items-start gap-3 rounded-xl border p-4 {{ $safetyDark ? 'border-white/10 bg-white/5 text-white/90' : 'border-primary/10 bg-surface-purple/40 text-primary-dark/85' }}"><x-waggies.icon name="check-circle" size="20" variant="filled" class="shrink-0 {{ $safetyDark ? 'text-secondary' : 'text-primary' }}" /><span class="text-sm font-medium">{{ $bullet }}</span></div>@endforeach</div><x-waggies.button href="{{ route('contact') }}" class="{{ $safetyDark ? 'bg-secondary! text-primary-dark!' : '' }}">{{ $page['safety']['linkLabel'] }} <x-waggies.icon name="arrow-forward" size="16" /></x-waggies.button></div></div></div></section>

<section class="border-t border-primary/5 bg-surface-purple/50 py-16"><div class="page-container"><x-waggies.cta-primary :cta="$page['cta']" /></div></section>

<section class="border-t border-surface-purple bg-white py-16" aria-label="Other boarding options"><div class="page-container"><x-waggies.section-heading eyebrow="More Boarding" title="Explore Our Other Boarding Options" subtitle="Every species gets a dedicated environment - find the right stay for your pet." spacing="mb-10"/><div class="grid grid-cols-1 gap-6 md:grid-cols-2">@foreach(array_values(array_filter($siblings, fn (array $s): bool => $s['key'] !== $species)) as $sibling)<a href="{{ route('services.boarding.species', ['species' => $sibling['key']]) }}" class="group flex gap-5 rounded-2xl border border-surface-purple bg-surface-purple/30 p-5 transition hover:bg-surface-purple hover:shadow-soft focus:outline-none focus:ring-2 focus:ring-primary/60 focus:ring-offset-2"><img src="{{ asset($sibling['image']) }}" alt="" class="size-24 shrink-0 rounded-xl object-cover transition-transform group-hover:scale-[1.02]" loading="lazy" aria-hidden="true" /><div class="min-w-0"><div class="mb-1 flex items-center gap-2"><x-waggies.icon name="{{ $sibling['icon'] }}" size="18" class="text-primary transition-colors" /><h3 class="font-serif font-bold text-primary-dark transition-colors group-hover:text-primary">{{ $sibling['title'] }}</h3></div><p class="text-sm leading-relaxed text-primary-dark/60">{{ $sibling['desc'] }}</p><span class="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-primary group-hover:underline">Learn more <x-waggies.icon name="arrow-forward" size="14" /></span></div></a>@endforeach</div></div></section>

<x-waggies.proof-band variant="boarding-{{ $species }}" />
<section class="bg-surface border-t border-primary/5 py-16"><div class="page-container"><x-waggies.section-heading eyebrow="FAQs" title="Frequently Asked Questions" spacing="mb-8"/><x-waggies.faq-accordion :faqs="$faqs" /><p class="mt-6 text-center text-sm text-primary-dark/60">More questions? <a href="{{ route('faq') }}" class="font-bold text-primary hover:underline">View all FAQs</a> or <a href="{{ route('contact') }}" class="font-bold text-primary hover:underline">contact us</a>.</p></div></section>
<div class="page-container py-4"><x-waggies.share-row :title="$shareTitle" :description="$shareDescription" /></div>

@endsection
