<?php

return [
    'grooming' => [
        'title' => 'Pet Grooming Spa', 'eyebrow' => 'Grooming Spa · Abuja', 'ctaText' => 'Request Grooming', 'ctaRoute' => 'contact', 'ctaParams' => ['intent' => 'service', 'service' => 'grooming'],
        'description' => 'Our groomers use gentle handling and non-toxic, pet-safe products in a peaceful setting designed to keep your pet relaxed from drop-off to pickup.',
        'hero' => ['imageSrc' => 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=1200&h=600&fit=crop&q=80', 'imageAlt' => 'Pet grooming spa at Waggies Abuja', 'description' => 'Breed-specific treatments, baths, and precision styling by experienced groomers in a calm, purpose-built spa.'],
        'features' => ['Bath with breed-specific shampoo and conditioner', 'Professional blow-dry and brush-out for a flawless finish', 'Breed-standard precision cut and styling by experienced groomers', 'Deep de-shed treatment to dramatically reduce loose fur', 'Gentle facial wash, eye cleaning, and ear inspection', 'Safe nail trim and grind to a comfortable length', 'Teeth brushing with pet-safe enzymatic toothpaste', 'Light cologne spritz and bandana finishing touch', 'Anal gland expression (upon request)', 'Sanitary trim and paw pad tidy-up', 'Flea and tick bath treatment available', 'Blueberry facial for tear stain removal'],
        'benefits' => ['All groomers are professionally trained and experienced — your pet is in expert hands every time.', 'We use only quality, non-toxic, pet-safe shampoos and conditioners — no harsh chemicals.', 'Patient, low-stress handling techniques especially for nervous or anxious pets.', 'We respect your time — drop-off and collection slots run to schedule, every single day.', 'Full photo report sent after every groom so you can see the results before pickup.', 'Breed-specific expertise means your pet gets a cut that suits their coat type and breed standard.'],
        'packages' => [
            ['name' => 'Bath & Brush', 'pricingKey' => 'bath', 'duration' => '45-60 min', 'features' => ['Shampoo bath', 'Blow-dry', 'Brush-out', 'Ear cleaning', 'Nail trim']],
            ['name' => 'Full Groom', 'pricingKey' => 'full', 'duration' => '90-120 min', 'popular' => true, 'features' => ['Bath & Brush', 'Breed-standard clip and styling', 'Teeth brushing', 'De-shed treatment', 'Finish']],
            ['name' => 'Luxury Spa', 'pricingKey' => 'spa', 'duration' => '2-3 hours', 'features' => ['Full Groom', 'Conditioning treatment', 'Facial and paw treatment', 'Flea/tick inspection', 'Photo report']],
        ],
        'standards' => ['eyebrow' => 'THE SPA EXPERIENCE', 'title' => 'How Every Groom Works', 'subtitle' => 'Four deliberate steps to ensure your pet leaves clean, relaxed, and looking their best.', 'cards' => [['number' => '01', 'title' => 'Coat & Skin Check', 'desc' => 'Personalised consultation to inspect coat condition, skin sensitivity, and breed styling requirements.'], ['number' => '02', 'title' => 'Hydrobath & Massage', 'desc' => 'Relaxing warm bath using pet-safe, natural shampoos and deep conditioning treatments.'], ['number' => '03', 'title' => 'Precision Styling & Dry', 'desc' => 'Gentle blow-dry, hand brush-out, and breed-standard scissors or clipper styling by expert groomers.'], ['number' => '04', 'title' => 'Finishing & Photo Report', 'desc' => 'Nail grind, ear tidy, light fragrance spritz, and a photo report sent straight to your phone.']]],
        'shareTitle' => 'Pet Grooming Spa - Waggies', 'shareDescription' => 'Breed-specific pet grooming in Abuja: baths, precision styling, nail trims, and de-shed treatments by experienced groomers.',
        'meta' => ['title' => 'Pet Grooming Spa', 'description' => 'Breed-specific pet grooming in Abuja: baths, precision styling, nail trims, and de-shed treatments by experienced groomers.'],
    ],
    'training' => [
        'title' => 'Dog Training', 'eyebrow' => 'Dog Training · Abuja', 'ctaText' => 'Request Training', 'ctaRoute' => 'contact', 'ctaParams' => ['intent' => 'service', 'service' => 'training'],
        'description' => "Our trainers use only reward-based, force-free methods. Whether you're starting with a new puppy or working through behavioural challenges, we design a programme that fits your dog's temperament and your goals.",
        'hero' => ['imageSrc' => 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=1200&h=600&fit=crop&q=80', 'imageAlt' => 'Dog training session at Waggies Abuja', 'description' => 'Science-based, positive-reinforcement training programmes for puppies and adult dogs — building confidence, manners, and a stronger bond.'],
        'features' => ['Puppy socialisation, recall, and bite inhibition (8-16 weeks)', 'Basic obedience — sit, stay, come, heel, and leash manners', 'Advanced obedience — off-lead reliability and distance commands', 'Behaviour modification for reactivity, anxiety, and aggression', 'Small group classes for socialisation and real-world practice', "1-to-1 private sessions tailored to your dog's specific needs", 'Clicker training and marker-based positive reinforcement', 'Loose-lead walking and polite greeting training', 'Separation anxiety management programmes', 'Trick training for mental stimulation and fun', 'Follow-up sessions and progress tracking included', 'Written training plan and homework for between sessions'],
        'benefits' => ['Reward-based, force-free methods only — we never use aversive tools or punishment-based techniques.', 'All trainers are experienced in canine behaviour and positive-reinforcement training methods.', 'Training that strengthens the relationship between you and your dog — bond-building focus.', 'Clear goals set at the outset and tracked throughout the programme — measurable progress.', 'Flexible scheduling — weekday, weekend, and evening session slots available.', 'Small class sizes (max 6 dogs) ensure every dog gets personal attention.'],
        'packages' => [['name' => 'Puppy Foundation', 'pricingKey' => 'puppy', 'duration' => '6 sessions · 45 min each', 'features' => ['Socialisation', 'Sit, stay, recall foundation', 'Bite inhibition and toilet training', 'Leash introduction', 'Puppy manual and homework']], ['name' => 'Basic Obedience', 'pricingKey' => 'obedience', 'duration' => '8 sessions · 60 min each', 'popular' => true, 'features' => ['Basic commands', 'Leash manners and heel', 'Polite greetings', 'Distraction proofing', 'Written training plan', 'Progress tracking']], ['name' => 'Behaviour Modification', 'price' => 'Custom quote', 'duration' => 'Assessment-led', 'features' => ['1-to-1 behavioural assessment', 'Custom modification plan', 'Reactivity and anxiety work', 'Environmental management', 'Ongoing trainer support']]],
        'standards' => ['eyebrow' => 'OUR METHODOLOGY', 'title' => 'Science-Based Dog Training', 'subtitle' => 'Positive reinforcement techniques that build trust, clear communication, and reliable manners.', 'cards' => [['icon' => 'achievement', 'title' => 'Reward-Based & Force-Free', 'desc' => 'We use science-backed positive reinforcement — no choke chains, prong collars, or punitive techniques.'], ['icon' => 'behavior', 'title' => 'Temperament-Tailored', 'desc' => "Every dog's learning style is unique. We adapt exercises to your dog's motivation, energy, and confidence level."], ['icon' => 'team', 'title' => 'Small Class Sizes', 'desc' => 'Group classes are capped at 6 dogs to ensure personalized trainer feedback and safe socialisation.'], ['icon' => 'training', 'title' => 'Homework & Written Plans', 'desc' => 'Every session includes clear action steps, video recaps, and homework guides to ensure lasting results at home.']]],
        'shareTitle' => 'Dog Training - Waggies', 'shareDescription' => 'Science-based, positive-reinforcement dog training in Abuja for puppies and adults - obedience, behaviour modification, and group classes.',
        'meta' => ['title' => 'Dog Training', 'description' => 'Science-based, positive-reinforcement dog training in Abuja for puppies and adults - obedience, behaviour modification, and group classes.'],
    ],
    'vet-care' => [
        'title' => 'Veterinary Care', 'eyebrow' => 'On-Site Vet Care · Abuja', 'ctaText' => 'Request Appointment', 'ctaRoute' => 'contact', 'ctaParams' => ['intent' => 'veterinary', 'service' => 'vet-care'],
        'description' => 'Having a veterinarian on-site every day gives pet parents total confidence. Whether your pet needs a routine check-up, vaccination booster, or medical attention while boarding, our care team is ready.',
        'hero' => ['imageSrc' => 'https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=1200&h=600&fit=crop&q=80', 'imageAlt' => 'Veterinary care at Waggies Abuja', 'description' => 'Consultations, vaccinations, wellness checks, and minor treatments — delivered by our on-site veterinarian every day of the week.'],
        'features' => ['Full nose-to-tail wellness examinations and health consultations', 'Core and non-core vaccinations on a personalised schedule', 'Routine wellness check-ups to catch issues early', 'Diagnosis, prescriptions, and minor treatment for common conditions', 'Flea, tick, and worm treatments and prevention advice', 'In-clinic diagnostic tests and external lab coordination', 'Dental examination, scaling, and minor dental procedures', 'Microchipping for permanent pet identification', 'Pre-travel health certificates and documentation', 'Weight monitoring and nutritional counselling', 'Spay/neuter consultations and scheduling', 'Emergency first aid and stabilisation'],
        'benefits' => ['Our vet is present on-site every day of the week, including weekends — no separate trip needed.', 'All vet services are delivered to certified professional standards — PCSA registered.', 'Boarding guests receive immediate veterinary attention if any concern arises during their stay.', 'Consultations happen in a calm, familiar setting — significantly less anxiety for your pet.', 'Full medical records maintained digitally for easy access and continuity of care.', 'Vaccination reminders sent automatically so you never miss a booster.'],
        'packages' => [['name' => 'Wellness Consultation', 'pricingKey' => 'consultation', 'duration' => '20-30 min', 'features' => ['Full physical examination', 'Weight and temperature check', 'Health assessment report', 'Diet and exercise advice']], ['name' => 'Vaccination Visit', 'pricingKey' => 'vaccination', 'duration' => '30-45 min', 'popular' => true, 'features' => ['Wellness check included', 'Core vaccines', 'Vaccination certificate', 'Booster reminders']], ['name' => 'Comprehensive Exam', 'pricingKey' => 'comprehensive-exam', 'duration' => '45-60 min', 'features' => ['Extended physical exam', 'Blood work and lab tests', 'Dental assessment', 'Full health report', 'Follow-up consultation']], ['name' => 'Treatment Plan', 'price' => 'Custom quote', 'duration' => 'By assessment', 'features' => ['Diagnosis and prescriptions']]],
        'standards' => ['eyebrow' => 'VETERINARY STANDARDS', 'title' => 'Why Pet Parents Trust Our Vet Care', 'subtitle' => 'Professional clinical standards combined with compassionate, low-stress handling.', 'cards' => [['icon' => 'safety', 'title' => 'On-Site Daily Doctor', 'desc' => 'A licensed veterinarian present 7 days a week, ensuring immediate attention for routine care or unexpected guest needs.'], ['icon' => 'veterinary-care', 'title' => 'Nose-to-Tail Exams', 'desc' => 'Comprehensive physical check-ups covering cardiac, dental, otic, ocular, and musculoskeletal health.'], ['icon' => 'calendar', 'title' => 'Digital Records & Boosters', 'desc' => 'All health records are securely stored digitally with automated booster reminders so your pet stays protected.'], ['icon' => 'hours', 'title' => 'Calm, Familiar Setting', 'desc' => 'Examinations take place in a quiet, low-stress environment without the chaos of a crowded waiting room.']]],
        'shareTitle' => 'Veterinary Care - Waggies', 'shareDescription' => 'Veterinary consultations, vaccinations, wellness check-ups and minor treatments from our on-site vet - every day at Waggies Abuja.',
        'meta' => ['title' => 'Veterinary Care', 'description' => 'Veterinary consultations, vaccinations, wellness check-ups and minor treatments from our on-site vet - every day at Waggies Abuja.'],
    ],
];
