<?php

return [
    'index' => [
        'title' => 'Pet Boarding',
        'description' => 'Pet boarding in Abuja with 24/7 supervision, private suites, on-site vet, and daily photo updates.',
        'hero' => ['imageSrc' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=1200&h=600&fit=crop&q=80', 'imageAlt' => 'Stock photo of happy dog (client photo required)', 'eyebrow' => 'Pet Boarding in Abuja', 'eyebrowIcon' => 'pets', 'title' => 'A Home Away From Home', 'subtitle' => 'Spacious, climate-controlled suites with 24/7 supervision, orthopedic bedding, and daily updates for total peace of mind.', 'cta' => ['label' => 'View Pricing & Estimates', 'route' => 'services.pricing', 'params' => ['service' => 'boarding'], 'icon' => 'payments']],
        'cards' => [
            ['title' => 'Dog Boarding', 'description' => 'Private suites with outdoor play areas, socialisation sessions, and daily grooming.', 'route' => 'services.boarding.species', 'params' => ['species' => 'dogs'], 'imageSrc' => 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=600&h=400&fit=crop&q=80', 'imageAlt' => 'Happy dogs at Waggies', 'icon' => 'pets'],
            ['title' => 'Cat Boarding', 'description' => 'Calm, quiet cat condos away from dogs - with enrichment toys and cosy resting nooks.', 'route' => 'services.boarding.species', 'params' => ['species' => 'cats'], 'imageSrc' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=400&fit=crop&q=80', 'imageAlt' => 'Cat in a boarding condo', 'icon' => 'cat'],
            ['title' => 'Exotic Boarding', 'description' => 'Specialist care for birds, reptiles, rabbits and small mammals in custom enclosures.', 'route' => 'services.boarding.species', 'params' => ['species' => 'exotic'], 'imageSrc' => 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=600&h=400&fit=crop&q=80', 'imageAlt' => 'Exotic pet in a specialist enclosure', 'icon' => 'exotic-pet'],
        ],
        'included' => [
            ['icon' => 'boarding', 'title' => 'Boarding Suites', 'desc' => 'Climate-controlled rooms with orthopedic bedding.'], ['icon' => 'nutrition', 'title' => 'Quality Meals', 'desc' => "Nutritious food served on your pet's usual schedule."], ['icon' => 'exercise', 'title' => 'Daily Exercise', 'desc' => 'Structured play and exercise sessions every day.'], ['icon' => 'veterinary-care', 'title' => 'Vet on Site', 'desc' => 'Our on-site vet monitors all boarding guests daily.'], ['icon' => 'notifications', 'title' => 'Daily Photo Updates', 'desc' => 'Photo and report sent to you every single day.'], ['icon' => 'safety', 'title' => '24/7 Supervision', 'desc' => 'Staff present around the clock - never unsupervised.'],
        ],
    ],
    'species' => [
        'dogs' => [
            'title' => 'Dog Boarding', 'description' => 'Premium dog boarding in Abuja with private suites, outdoor play areas, socialisation sessions, and 24/7 supervision.',
            'hero' => ['imageSrc' => '/service-hero-boarding-dogs.jpg', 'imageAlt' => 'Happy dogs socialising in the secure outdoor paddock at Waggies', 'eyebrow' => 'Dog Boarding', 'eyebrowIcon' => 'pets', 'title' => 'A Safe, Structured Stay for Your Dog', 'subtitle' => "Private suites, supervised play, and daily routines designed to keep your dog active and comfortable while you're away.", 'cta' => ['label' => 'Book Boarding', 'route' => 'contact', 'params' => ['intent' => 'book', 'service' => 'boarding', 'variant' => 'dogs'], 'icon' => 'arrow-forward'], 'secondaryCta' => ['label' => 'Get Estimate', 'route' => 'services.pricing', 'params' => ['service' => 'boarding-dogs'], 'iconBefore' => 'calculator']],
            'stats' => [['value' => '5k+', 'label' => 'Happy Pet Guests'], ['value' => '24/7', 'label' => 'On-Site Supervision'], ['value' => '2×', 'label' => 'Daily Exercise Sessions'], ['value' => '100%', 'label' => 'Vaccination Verified']],
            'activityHighlights' => [['icon' => 'dog', 'title' => 'Outdoor Paddocks', 'desc' => 'Grassy yards with secure double-gated fencing.'], ['icon' => 'energy', 'title' => 'Matched Playgroups', 'desc' => 'Grouped by size, energy, and temperament.'], ['icon' => 'hours', 'title' => '2x Daily Walks', 'desc' => 'Structured routine exercise every morning & evening.'], ['icon' => 'verified', 'title' => '24/7 Supervision', 'desc' => 'On-site canine care staff and daily vet checks.']],
            'packageHeading' => ['eyebrow' => 'Dog Boarding Packages', 'title' => 'Find the Right Stay for Your Dog', 'subtitle' => "From simple overnight stays to fully supervised care with extra comfort and attention - choose a package that matches your dog's needs and routine."],
            'featuresHeading' => ['eyebrow' => "What's Included", 'title' => 'Everything Your Dog Needs', 'subtitle' => 'Structured care, enrichment, and comfort - all handled by trained dog-care staff.'],
            'features' => [['icon' => 'boarding', 'title' => 'Private Suites', 'desc' => 'Climate-controlled rooms sized for your dog, with bedding refreshed daily.'], ['icon' => 'play', 'title' => 'Supervised Play', 'desc' => 'Group or solo sessions in secure paddocks, matched by size and temperament.'], ['icon' => 'nutrition', 'title' => 'Tailored Feeding', 'desc' => 'Meals on your schedule using your food or our premium kibble.'], ['icon' => 'veterinary-care', 'title' => 'Daily Vet Checks', 'desc' => 'On-site vet monitors all guests and responds quickly to any concerns.'], ['icon' => 'notifications', 'title' => 'Photo Updates', 'desc' => 'Daily photos and notes so you always know how your dog is doing.'], ['icon' => 'grooming', 'title' => 'Optional Grooming', 'desc' => 'Add a bath, brush, or full groom during their stay on Premium and Deluxe packages.']],
            'daily' => ['heading' => 'A Day in the Life for Dogs', 'subtitle' => 'We keep tails wagging from sunrise to sunset with a structured routine of fun, food, and rest.', 'steps' => [['icon' => 'daylight', 'title' => '7:00 AM - Rise & Shine', 'description' => 'First potty walk and fresh water service.'], ['icon' => 'nutrition', 'title' => '8:00 AM - Breakfast', 'description' => 'Premium kibble or owner-provided meals served individually.'], ['icon' => 'play', 'title' => '9:30 AM - Group Play', 'description' => 'Supervised socialisation in secure outdoor paddocks.'], ['icon' => 'rest', 'title' => '12:00 PM - Rest Time', 'description' => 'Quiet rest in climate-controlled suites.'], ['icon' => 'night', 'title' => '8:00 PM - Tuck In', 'description' => 'Final potty break, bedtime treats, and soothing music.']], 'images' => ['https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=800&h=600&fit=crop&q=80']],
            'safety' => ['title' => 'Safety First Policy', 'intro' => 'Every dog undergoes a health check and vaccination verification before admission. Dogs are grouped by size and temperament, and all play sessions are actively supervised by trained staff.', 'bullets' => ['Vaccination and flea/tick verification required on arrival', 'Dogs separated by size, temperament, and energy level', 'Staff-supervised play sessions throughout the day', 'Emergency vet protocol in place for all boarding dogs'], 'linkLabel' => 'Ask about boarding requirements'],
            'cta' => ['heading' => "Ready to Book Your Dog's Stay?", 'body' => 'Secure a safe, structured boarding experience with daily updates and supervised routines.', 'primaryLabel' => 'Book Boarding', 'primaryRoute' => 'contact', 'secondaryLabel' => 'View All Pricing', 'secondaryRoute' => 'services.pricing'],
        ],
        'cats' => [
            'title' => 'Cat Boarding', 'description' => 'Calm cat boarding in Abuja with private condos, a dog-free wing, enrichment, and attentive daily care.',
            'hero' => ['imageSrc' => '/service-hero-boarding-cats.jpg', 'imageAlt' => 'Relaxed cat in a calm, dog-free boarding condo at Waggies', 'eyebrow' => 'Cat Boarding', 'eyebrowIcon' => 'pets', 'title' => 'Calm, Cosy Stays for Your Cat', 'subtitle' => 'Quiet cat condos in a dog-free wing - with enrichment, cosy nooks, and attentive care from cat-specialist staff.', 'cta' => ['label' => 'Book a Stay', 'route' => 'contact', 'params' => ['intent' => 'book', 'service' => 'boarding', 'variant' => 'cats'], 'icon' => 'arrow-forward'], 'secondaryCta' => ['label' => 'Get Estimate', 'route' => 'services.pricing', 'params' => ['service' => 'boarding-cats'], 'iconBefore' => 'calculator']],
            'stats' => [['value' => '100%', 'label' => 'Dog-Free Cat Wing'], ['value' => '24/7', 'label' => 'Quiet Monitoring'], ['value' => 'Daily', 'label' => 'Photo Updates'], ['value' => '3', 'label' => 'Condo Size Options']],
            'sanctuary' => ['eyebrow' => '100% Dog-Free Sanctuary Guarantee', 'title' => 'A Quiet, Stress-Free Environment for Felines', 'body' => 'Our cat wing is completely separated from dog areas with dedicated air circulation, soft lighting, and zero canine sight or sound exposure.', 'badges' => [['icon' => 'privacy', 'label' => 'No Barking Sounds'], ['icon' => 'home', 'label' => 'Multi-Level Condos']]],
            'packageHeading' => ['eyebrow' => 'Cat Boarding Packages', 'title' => 'Find the Right Condo for Your Cat', 'subtitle' => 'From a peaceful overnight to extra enrichment and vet monitoring - every package respects how cats like to live.'],
            'featuresHeading' => ['eyebrow' => 'Cat Boarding Includes', 'title' => 'A Calm Environment for Cats', 'subtitle' => 'Cats are sensitive travellers. Our cat wing is calm, dog-free, and designed around feline behaviour.'],
            'features' => [['icon' => 'boarding', 'title' => 'Private Cat Condos', 'desc' => 'Multi-level condos with hammocks, perches, and cosy hideaway nooks.'], ['icon' => 'privacy', 'title' => 'Dog-Free Zone', 'desc' => 'Our cat wing is fully separate - cats never share corridors or outdoor areas with dogs.'], ['icon' => 'play', 'title' => 'Daily Enrichment', 'desc' => 'Puzzle feeders, interactive toys, and gentle one-on-one play tailored to your cat.'], ['icon' => 'nutrition', 'title' => 'Tailored Feeding', 'desc' => "Meals on your cat's usual schedule using your preferred brand or our quality food."], ['icon' => 'veterinary-care', 'title' => 'Vet Monitoring', 'desc' => 'On-site vet checks all cat guests daily and addresses health concerns immediately.'], ['icon' => 'notifications', 'title' => 'Daily Photo Updates', 'desc' => 'Photos and a brief note every day so you always know how your cat is settling in.']],
            'daily' => ['heading' => 'A Day in the Life for Cats', 'subtitle' => 'A calm, predictable rhythm that helps even shy cats feel secure - never rushed, never forced.', 'steps' => [['icon' => 'daylight', 'title' => '7:30 AM - Gentle Start', 'description' => 'Quiet check-in, fresh water, and litter refresh without disruption.'], ['icon' => 'nutrition', 'title' => '8:30 AM - Breakfast', 'description' => "Meals served in-suite on your cat's usual schedule."], ['icon' => 'play', 'title' => '11:00 AM - Enrichment', 'description' => 'Puzzle feeders, wand play, or solo exploration in the private playroom.'], ['icon' => 'rest', 'title' => '2:00 PM - Rest Period', 'description' => 'Lights dimmed for afternoon naps - staff keep noise levels low.'], ['icon' => 'night', 'title' => '8:00 PM - Evening Settle', 'description' => 'Dinner, final litter check, and a calm goodnight routine.']], 'images' => ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800&h=600&fit=crop&q=80']],
            'feline' => ['eyebrow' => 'Why Cats Love Waggies', 'title' => 'Built for Feline Instincts', 'body' => 'Vertical space, privacy, and predictable routines - the three things cats need most when away from home.', 'bullets' => [['bold' => 'No dog noise or smells', 'text' => ' - reduces stress for even the most anxious cats.'], ['bold' => 'Bring bedding and toys', 'text' => ' - familiar scents make settling in much faster.'], ['bold' => 'Cat-specialist staff', 'text' => ' - trained in low-stress handling and reading feline body language.']], 'image' => 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?auto=format&fit=crop&w=900&q=80', 'imageAlt' => 'Cat relaxing in a multi-level boarding condo'],
            'safety' => ['title' => 'Feline Safety & Comfort Standards', 'intro' => 'We never force interaction. Shy cats get extra settling time, familiar scents from home are welcome, and every condo has elevated perches and hiding spots.', 'bullets' => ['Vaccination records verified before check-in', 'Fully dog-free wing with separate air circulation', 'Medication administered precisely to your instructions', 'Immediate vet assessment if appetite or behaviour changes'], 'linkLabel' => "Discuss your cat's needs"],
            'cta' => ['heading' => "Ready to Book Your Cat's Stay?", 'body' => 'Reserve a calm, dog-free condo with daily updates and care from staff who understand cats.', 'primaryLabel' => 'Book Cat Boarding', 'primaryRoute' => 'contact', 'secondaryLabel' => 'View All Pricing', 'secondaryRoute' => 'services.pricing'],
        ],
        'exotic' => [
            'title' => 'Exotic Pet Boarding', 'description' => 'Specialist exotic pet boarding in Abuja with custom enclosures, climate monitoring, and species-appropriate care.',
            'hero' => ['imageSrc' => '/service-hero-boarding-exotic.jpg', 'imageAlt' => 'Colourful parrots in a specialist exotic pet care environment at Waggies', 'eyebrow' => 'Exotic Pet Boarding', 'eyebrowIcon' => 'exotic-pet', 'title' => 'Specialist Care for Exotic Pets', 'subtitle' => 'Birds, reptiles, rabbits, guinea pigs, and small mammals - cared for by specialist staff in custom-built, species-appropriate enclosures.', 'cta' => ['label' => 'Enquire Now', 'route' => 'contact', 'params' => ['intent' => 'consult', 'service' => 'boarding', 'variant' => 'exotic'], 'icon' => 'arrow-forward'], 'secondaryCta' => ['label' => 'Get Estimate', 'route' => 'services.pricing', 'params' => ['service' => 'boarding-exotic'], 'iconBefore' => 'calculator']],
            'stats' => [['value' => '50+', 'label' => 'Species Experience'], ['value' => '24/7', 'label' => 'Climate Monitoring'], ['value' => '100%', 'label' => 'Custom Enclosures'], ['value' => 'Daily', 'label' => 'Care Updates']],
            'environment' => ['eyebrow' => 'ENVIRONMENTAL PRECISION', 'title' => 'Species-Specific Climate & Care Protocols', 'badge' => 'Specialist Handlers & Vet Supervision', 'features' => [['icon' => 'climate', 'title' => 'Thermal Gradients', 'desc' => 'Basking spots & cool retreat zones logged twice daily.'], ['icon' => 'daylight', 'title' => 'UVB & Lighting', 'desc' => 'Strict photoperiod timers matched to native habitat needs.'], ['icon' => 'water', 'title' => 'Humidity Control', 'desc' => 'Misting & misting cycles tailored for tropical or arid species.'], ['icon' => 'medical', 'title' => 'Live Feeder Handling', 'desc' => 'Live or frozen feeder protocols executed to exact instructions.']]],
            'packageHeading' => ['eyebrow' => 'Exotic Boarding Packages', 'title' => 'Care Matched to Your Species', 'subtitle' => "Pricing reflects enclosure complexity and specialist handling - we'll confirm exact rates when you enquire."],
            'featuresHeading' => ['eyebrow' => "What's Included", 'title' => 'Tailored Care for Every Species', 'subtitle' => null],
            'features' => [['icon' => 'home', 'title' => 'Species-Specific Enclosures', 'desc' => 'Custom housing with correct temperature, humidity, and lighting for each species.'], ['icon' => 'nutrition', 'title' => 'Specialist Diet', 'desc' => "Feeding according to each animal's dietary needs and your usual routine - including live feeders when required."], ['icon' => 'veterinary-care', 'title' => 'Exotic Vet Access', 'desc' => 'Our vet has experience with exotic and small animals and reviews guests daily.'], ['icon' => 'notifications', 'title' => 'Regular Updates', 'desc' => 'Photo updates so you can check in on your pet throughout their stay.'], ['icon' => 'safety', 'title' => '24/7 Monitoring', 'desc' => 'Staff check on exotic guests throughout the day and night, including climate systems.'], ['icon' => 'behavior', 'title' => 'Experienced Handlers', 'desc' => 'Trained staff who understand handling, stress signals, and species-specific behaviour.']],
            'species' => [['label' => 'Birds', 'icon' => 'exotic-pet', 'desc' => 'High-volume flight space, perches & daily fresh seed/fruit feeds.'], ['label' => 'Reptiles', 'icon' => 'parasite', 'desc' => 'Thermal gradient zones, UVB photoperiods & humidity logging.'], ['label' => 'Rabbits', 'icon' => 'exotic-pet', 'desc' => 'Spacious exercise runs, unlimited timothy hay & solid flooring.'], ['label' => 'Guinea Pigs', 'icon' => 'exotic-pet', 'desc' => 'Quiet habitats, Vitamin C enriched diet & deep bedding.'], ['label' => 'Hamsters', 'icon' => 'pets', 'desc' => 'Secure escape-proof habitats with quiet nocturnal rest areas.'], ['label' => 'Aquatic / Others', 'icon' => 'water', 'desc' => 'Stable temperature control & custom feeding protocols.']],
            'featureBand' => ['eyebrow' => 'Before You Book', 'title' => 'What to Prepare for Check-In', 'subtitle' => 'A little preparation helps exotic pets settle faster and keeps their routine intact.', 'cta' => ['label' => 'Discuss Your Pet', 'route' => 'contact'], 'features' => [['icon' => 'document', 'title' => 'Written Care Sheet', 'description' => 'Feeding times, portion sizes, temperature ranges, and any handling preferences.'], ['icon' => 'supplies', 'title' => 'Supplies from Home', 'description' => 'Food, substrates, feeders, or habitat items your pet is used to - clearly labelled.'], ['icon' => 'verified', 'title' => 'Health Records', 'description' => 'Recent vet notes or vaccination records where applicable for your species.']]],
            'daily' => ['heading' => 'A Day in the Life for Exotic Guests', 'subtitle' => 'Precise routines for temperature, feeding, and handling - because exotic pets thrive on consistency.', 'steps' => [['icon' => 'daylight', 'title' => '7:00 AM - Habitat Check', 'description' => 'Temperature, humidity, UV, and water systems verified for each enclosure.'], ['icon' => 'nutrition', 'title' => '8:00 AM - Morning Feed', 'description' => 'Meals or feeders administered per your written protocol.'], ['icon' => 'visibility', 'title' => '12:00 PM - Health Observation', 'description' => 'Behaviour, appetite, and enclosure condition logged by specialist staff.'], ['icon' => 'climate', 'title' => '4:00 PM - Environment Review', 'description' => 'Climate adjustments and enrichment rotation as species require.'], ['icon' => 'night', 'title' => '8:00 PM - Evening Round', 'description' => 'Final checks, secure enclosures, and overnight monitoring handover.']], 'images' => ['https://images.unsplash.com/photo-1520808663317-647b476a81b9?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1535268647677-300dbf3d78d1?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1456926631375-92c8ce872def?w=800&h=600&fit=crop&q=80', 'https://images.unsplash.com/photo-1425082661705-1834bfd09dca?w=800&h=600&fit=crop&q=80']],
            'safety' => ['title' => 'Exotic Care & Safety Protocols', 'intro' => 'Every exotic booking starts with a pre-arrival consultation. We confirm species requirements, feeding instructions, and enclosure specifications before your pet arrives.', 'bullets' => ['Pre-stay consultation to confirm habitat and dietary needs', 'Owner-supplied feeders or equipment welcomed and labelled', 'Separate exotic wing - no contact with dogs or cats', 'Immediate vet escalation if behaviour or environment deviates'], 'linkLabel' => 'Start an exotic boarding enquiry'],
            'cta' => ['heading' => 'Enquire About Exotic Boarding', 'body' => "Tell us your species, setup, and dates - we'll confirm availability and build a care plan before check-in.", 'primaryLabel' => 'Get in Touch', 'primaryRoute' => 'contact', 'primaryParams' => ['intent' => 'consult', 'service' => 'boarding', 'variant' => 'exotic'], 'secondaryLabel' => 'Get Estimate', 'secondaryRoute' => 'services.pricing', 'secondaryParams' => ['service' => 'boarding-exotic']],
        ],
    ],
    'tiers' => [
        'dogs' => [['key' => 'basic', 'label' => 'Basic', 'price' => '₦10,000', 'unit' => '/night', 'featured' => false, 'features' => [['label' => '1 dog boarding suite', 'included' => true], ['label' => 'Daily outdoor walks', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Grooming service', 'included' => false]]], ['key' => 'premium', 'label' => 'Premium', 'price' => '₦18,000', 'unit' => '/night', 'featured' => true, 'badge' => 'Most Popular', 'features' => [['label' => '2 dogs boarding suite', 'included' => true], ['label' => 'Daily outdoor walks', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Grooming service', 'included' => true]]], ['key' => 'deluxe', 'label' => 'Deluxe', 'price' => '₦25,000', 'unit' => '/night', 'featured' => false, 'features' => [['label' => '3+ dogs family suite', 'included' => true], ['label' => 'Daily outdoor walks', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Grooming + spa bath', 'included' => true]]]],
        'cats' => [['key' => 'cozy', 'label' => 'Cozy', 'price' => '₦8,000', 'unit' => '/night', 'featured' => false, 'features' => [['label' => '1 private cat condo', 'included' => true], ['label' => 'Daily enrichment & perches', 'included' => true], ['label' => 'Daily photo updates', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Private playroom access', 'included' => false]]], ['key' => 'premium', 'label' => 'Premium', 'price' => '₦14,000', 'unit' => '/night', 'featured' => true, 'badge' => 'Most Popular', 'features' => [['label' => '2 cats (same condo)', 'included' => true], ['label' => 'Daily enrichment & perches', 'included' => true], ['label' => 'Daily photo & video updates', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Private playroom time', 'included' => true]]], ['key' => 'deluxe', 'label' => 'Deluxe', 'price' => '₦22,000', 'unit' => '/night', 'featured' => false, 'features' => [['label' => 'Deluxe multi-level condo', 'included' => true], ['label' => '1-on-1 play & cuddle time', 'included' => true], ['label' => 'Daily vet health check', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Complimentary coat groom', 'included' => true]]]],
        'exotic' => [['key' => 'small', 'label' => 'Small Mammal', 'price' => '₦6,000 - ₦8,000', 'unit' => '/night', 'featured' => false, 'features' => [['label' => 'Rabbits, guinea pigs, hamsters', 'included' => true], ['label' => 'Species-appropriate enclosure', 'included' => true], ['label' => 'Daily health check', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Climate-controlled reptile setup', 'included' => false]]], ['key' => 'specialist', 'label' => 'Specialist', 'price' => '₦12,000 - ₦15,000', 'unit' => '/night', 'featured' => true, 'badge' => 'Most Popular', 'features' => [['label' => 'Birds or reptiles', 'included' => true], ['label' => 'Temp, humidity & UV monitoring', 'included' => true], ['label' => 'Custom feeding protocol', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Daily photo updates', 'included' => true]]], ['key' => 'premium', 'label' => 'Premium Habitat', 'price' => 'Quote', 'unit' => '', 'featured' => false, 'features' => [['label' => 'Complex multi-zone enclosures', 'included' => true], ['label' => 'Live/frozen feeder handling', 'included' => true], ['label' => 'Exotic vet daily review', 'included' => true], ['label' => '24/7 supervision', 'included' => true], ['label' => 'Owner-supplied habitat setup', 'included' => true]]]],
    ],
];
