<?php

return [
    'testimonials' => [
        'hero' => [
            'eyebrow' => 'What Clients Say',
            'eyebrowIcon' => 'reviews',
            'title' => 'Trusted by Pet Owners<br />Across Abuja',
            'description' => 'Read what clients share about their Waggies experience.',
            'imageSrc' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop&q=80',
            'imageAlt' => 'Dog in a boarding suite',
            'primaryAction' => ['label' => 'Book a Stay', 'route' => 'services.boarding'],
            'secondaryAction' => ['label' => 'Contact Us', 'route' => 'contact'],
        ],
        'filters' => [
            ['value' => 'all', 'label' => 'All Services'],
            ['value' => 'boarding-dogs', 'label' => 'Dog Boarding'],
            ['value' => 'boarding-cats', 'label' => 'Cat Boarding'],
            ['value' => 'boarding-exotic', 'label' => 'Exotic Pet Boarding'],
            ['value' => 'grooming', 'label' => 'Grooming'],
            ['value' => 'vet-care', 'label' => 'Veterinary Care'],
            ['value' => 'training', 'label' => 'Training'],
            ['value' => 'relocation-import', 'label' => 'Pet Import'],
            ['value' => 'relocation-export', 'label' => 'Pet Export'],
            ['value' => 'local-transport', 'label' => 'Local Transport'],
            ['value' => 'general', 'label' => 'General'],
        ],
        'items' => [
            ['id' => 't-01', 'stars' => 5, 'quote' => "Waggies is the only place I'd trust with my dog. The daily photo updates gave me real peace of mind while I was travelling.", 'authorInitial' => 'A', 'authorName' => 'Adaeze O.', 'authorSubtitle' => 'Dog owner · Maitama', 'service' => 'boarding-dogs'],
            ['id' => 't-02', 'stars' => 5, 'quote' => "The grooming team transformed my Persian cat. She looked like she'd come straight from a pet show!", 'authorInitial' => 'E', 'authorName' => 'Emeka N.', 'authorSubtitle' => 'Cat owner · Wuse II', 'service' => 'grooming'],
            ['id' => 't-03', 'stars' => 5, 'quote' => 'Our relocation from London was seamless. Every document was sorted  -  zero stress on our end.', 'authorInitial' => 'F', 'authorName' => 'Fatima M.', 'authorSubtitle' => 'Relocation client · Asokoro', 'service' => 'relocation-import'],
            ['id' => 't-04', 'stars' => 5, 'quote' => "The facilities are genuinely world-class. I've boarded dogs in Dubai and London  -  Waggies is right up there.", 'authorInitial' => 'C', 'authorName' => 'Chukwudi B.', 'authorSubtitle' => 'Dog owner · Garki', 'service' => 'boarding-dogs'],
            ['id' => 't-05', 'stars' => 5, 'quote' => 'My puppy finished the training programme a completely different dog. Patient, focused and brilliant with him.', 'authorInitial' => 'N', 'authorName' => 'Ngozi T.', 'authorSubtitle' => 'Training client · Gwarinpa', 'service' => 'training'],
            ['id' => 't-06', 'stars' => 5, 'quote' => 'Brought my cat in for grooming after she got into a mess outside. Came back looking and smelling amazing. Great service.', 'authorInitial' => 'S', 'authorName' => 'Sola A.', 'authorSubtitle' => 'Cat owner · Jabi', 'service' => 'grooming'],
            ['id' => 't-07', 'stars' => 5, 'quote' => 'The vet saw my dog the same day I called. Thorough, professional and really genuinely caring. Exactly what we needed.', 'authorInitial' => 'K', 'authorName' => 'Kemi L.', 'authorSubtitle' => 'Dog owner · Utako', 'service' => 'vet-care'],
            ['id' => 't-08', 'stars' => 5, 'quote' => 'Transport service is brilliant  -  on time, air-conditioned and my dogs arrive calm every single time.', 'authorInitial' => 'Y', 'authorName' => 'Yemi F.', 'authorSubtitle' => 'Dog owner · Wuse', 'service' => 'local-transport'],
            ['id' => 't-09', 'stars' => 5, 'quote' => "We've used Waggies for boarding, grooming, and transport. Consistently excellent. Our pets love it.", 'authorInitial' => 'O', 'authorName' => 'Obiageli R.', 'authorSubtitle' => 'Multi-service client · Maitama', 'service' => 'general'],
            ['id' => 't-10', 'stars' => 5, 'quote' => 'Leaving my cat somewhere new always feels risky, but the cattery suites are calm, quiet and spotless. Mimi came home more relaxed than when she left.', 'authorInitial' => 'Z', 'authorName' => 'Zainab A.', 'authorSubtitle' => 'Cat owner · Life Camp', 'service' => 'boarding-cats'],
            ['id' => 't-11', 'stars' => 5, 'quote' => "Finding somewhere in Abuja that genuinely understands exotic pets is hard. The team knew exactly how to handle my African grey's diet and enrichment — proper specialists.", 'authorInitial' => 'T', 'authorName' => 'Tunde O.', 'authorSubtitle' => 'Exotic pet owner · Maitama', 'service' => 'boarding-exotic'],
            ['id' => 't-12', 'stars' => 5, 'quote' => 'Relocating to Toronto with my two dogs felt overwhelming until Waggies took over the export paperwork, vaccinations and flight crate. They handled every detail end to end.', 'authorInitial' => 'I', 'authorName' => 'Ifeoma D.', 'authorSubtitle' => 'Relocation client · Asokoro', 'service' => 'relocation-export'],
        ],
        'bottomCta' => [
            'heading' => 'See for yourself',
            'body' => 'Trusted by pet owners across Abuja for boarding, grooming, vet care, training and relocation.',
            'ctaLabel' => 'Get in Touch',
            'ctaRoute' => 'contact',
        ],
    ],
    'gallery' => [
        'hero' => [
            'eyebrow' => 'Photo Gallery',
            'title' => 'Take a Look Inside',
            'description' => 'Our facilities speak for themselves. Browse our boarding suites, grooming spa, veterinary clinic, training grounds, and the happy faces of our guests.',
        ],
        'images' => [
            ['src' => 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop&q=80', 'alt' => 'Golden retriever relaxing outdoors in a spacious green play area', 'category' => 'Boarding', 'groupTitle' => 'Boarding Suites & Play Areas'],
            ['src' => 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=600&h=400&fit=crop&q=80', 'alt' => 'Happy dog running and playing in lush green grass', 'category' => 'Boarding', 'groupTitle' => 'Boarding Suites & Play Areas'],
            ['src' => 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=400&fit=crop&q=80', 'alt' => 'Cute puppy resting comfortably in a cozy boarding suite', 'category' => 'Boarding', 'groupTitle' => 'Boarding Suites & Play Areas'],
            ['src' => 'https://images.unsplash.com/photo-1596854407944-bf87f6fdd49e?w=600&h=400&fit=crop&q=80', 'alt' => 'Cat and dog resting peacefully together in a shared boarding space', 'category' => 'Boarding', 'groupTitle' => 'Boarding Suites & Play Areas'],
            ['src' => 'https://images.unsplash.com/photo-1450778855892-8139e5e4f23f?w=600&h=400&fit=crop&q=80', 'alt' => 'Close-up of a cat looking calm and content in its boarding suite', 'category' => 'Boarding', 'groupTitle' => 'Boarding Suites & Play Areas'],
            ['src' => 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&h=400&fit=crop&q=80', 'alt' => 'Cat being gently groomed with a professional brush at the spa', 'category' => 'Grooming', 'groupTitle' => 'Grooming Spa'],
            ['src' => 'https://images.unsplash.com/photo-1607305389524-3e2de06068d5?w=600&h=400&fit=crop&q=80', 'alt' => 'Dog getting a warm bath during a grooming session', 'category' => 'Grooming', 'groupTitle' => 'Grooming Spa'],
            ['src' => 'https://images.unsplash.com/photo-1477884213160-51f6da289cc4?w=600&h=400&fit=crop&q=80', 'alt' => 'Cat being carefully brushed to a silky smooth coat', 'category' => 'Grooming', 'groupTitle' => 'Grooming Spa'],
            ['src' => 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=400&fit=crop&q=80', 'alt' => 'Elegant cat portrait after a professional grooming session', 'category' => 'Grooming', 'groupTitle' => 'Grooming Spa'],
            ['src' => 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=400&fit=crop&q=80', 'alt' => 'Orange tabby cat looking fresh and well-groomed', 'category' => 'Grooming', 'groupTitle' => 'Grooming Spa'],
            ['src' => 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=400&fit=crop&q=80', 'alt' => 'Veterinarian examining a dog during a routine health checkup', 'category' => 'Veterinary', 'groupTitle' => 'Veterinary Clinic'],
            ['src' => 'https://images.unsplash.com/photo-1535930749574-099f483c0958?w=600&h=400&fit=crop&q=80', 'alt' => 'Vet carefully examining a dog with a stethoscope in the clinic', 'category' => 'Veterinary', 'groupTitle' => 'Veterinary Clinic'],
            ['src' => 'https://images.unsplash.com/photo-1576201836106-1751265f008f?w=600&h=400&fit=crop&q=80', 'alt' => 'Puppy receiving a gentle health examination from the vet team', 'category' => 'Veterinary', 'groupTitle' => 'Veterinary Clinic'],
            ['src' => 'https://images.unsplash.com/photo-1583337130417-13273c02f1f8?w=600&h=400&fit=crop&q=80', 'alt' => 'Cat sleeping peacefully after a comfortable veterinary visit', 'category' => 'Veterinary', 'groupTitle' => 'Veterinary Clinic'],
            ['src' => 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=400&fit=crop&q=80', 'alt' => 'Dog focused and attentive during an obedience training session', 'category' => 'Training', 'groupTitle' => 'Training & Behaviour'],
            ['src' => 'https://images.unsplash.com/photo-1548767797-d96c944b7a63?w=600&h=400&fit=crop&q=80', 'alt' => 'Group of dogs participating in a professional training class', 'category' => 'Training', 'groupTitle' => 'Training & Behaviour'],
            ['src' => 'https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&h=400&fit=crop&q=80', 'alt' => 'Dog portrait showing the confident posture from behavioural training', 'category' => 'Training', 'groupTitle' => 'Training & Behaviour'],
            ['src' => 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=600&h=400&fit=crop&q=80', 'alt' => 'Adorable pug portrait demonstrating calm trained behaviour', 'category' => 'Training', 'groupTitle' => 'Training & Behaviour'],
            ['src' => 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=400&fit=crop&q=80', 'alt' => 'Young puppy beginning its first training lesson with the team', 'category' => 'Training', 'groupTitle' => 'Training & Behaviour'],
            ['src' => 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&h=400&fit=crop&q=80', 'alt' => 'Dog wearing a travel backpack ready for a relocation journey', 'category' => 'Relocation', 'groupTitle' => 'Pet Relocation & Transport'],
            ['src' => 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=400&fit=crop&q=80', 'alt' => 'Dog sitting comfortably inside a car during pet transport', 'category' => 'Relocation', 'groupTitle' => 'Pet Relocation & Transport'],
            ['src' => 'https://images.unsplash.com/photo-1582562124811-c09040d0a901?w=600&h=400&fit=crop&q=80', 'alt' => 'Pet carrier prepared and ready for safe animal relocation', 'category' => 'Relocation', 'groupTitle' => 'Pet Relocation & Transport'],
            ['src' => 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=400&fit=crop&q=80', 'alt' => 'Golden retriever calmly waiting for the next leg of its relocation trip', 'category' => 'Relocation', 'groupTitle' => 'Pet Relocation & Transport'],
        ],
    ],
    'careers' => [
        'hero' => [
            'imageSrc' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1200&h=600&fit=crop&q=80',
            'imageAlt' => 'A diverse pet-care team',
            'eyebrow' => 'Careers',
            'title' => 'Join the Waggies Pack',
            'description' => "Build a career doing what you love — caring for pets in Abuja's premier pet care facility.",
            'primaryAction' => ['label' => 'View Open Roles', 'href' => '#open-roles'],
        ],
        'perksHeading' => ['eyebrow' => 'Why Waggies', 'title' => 'Perks & Benefits', 'subtitle' => 'We invest in our team because our people are the heart of everything we do.'],
        'perks' => [
            ['icon' => 'training', 'title' => 'Paid Training', 'desc' => 'Fully funded professional development and certification for all team members.'],
            ['icon' => 'favorite', 'title' => 'Do What You Love', 'desc' => 'Spend your working day doing something that genuinely matters to you.'],
            ['icon' => 'team', 'title' => 'Great Team Culture', 'desc' => 'A tight-knit, supportive team that looks out for each other.'],
            ['icon' => 'progress', 'title' => 'Room to Grow', 'desc' => 'We promote from within and invest in the long-term careers of our staff.'],
        ],
        'openRolesHeading' => ['eyebrow' => 'Open Roles', 'title' => 'Current Vacancies'],
        'openRoles' => [
            ['role' => 'Pet Groomer', 'dept' => 'Grooming', 'type' => 'Full-time', 'applyRoute' => 'contact', 'applyLabel' => 'Apply Now'],
            ['role' => 'Veterinary Technician', 'dept' => 'Veterinary', 'type' => 'Full-time', 'applyRoute' => 'contact', 'applyLabel' => 'Apply Now'],
            ['role' => 'Kennel Attendant', 'dept' => 'Boarding', 'type' => 'Full-time', 'applyRoute' => 'contact', 'applyLabel' => 'Apply Now'],
            ['role' => 'Dog Trainer', 'dept' => 'Training', 'type' => 'Part-time', 'applyRoute' => 'contact', 'applyLabel' => 'Apply Now'],
        ],
        'speculativeNote' => "Don't see a role that fits? We're always open to hearing from passionate pet lovers. Send us your CV and we'll keep you in mind.",
    ],
    'partnerships' => [
        'hero' => ['eyebrow' => 'Partnerships', 'title' => 'Better Together', 'description' => 'We partner with aligned organisations  -  vets, breeders, pet retailers, and businesses  -  who share our commitment to animal welfare and quality care.'],
        'typesHeading' => ['eyebrow' => 'Partnership Types', 'title' => 'How We Work<br/>With Partners', 'subtitle' => "Whether you're a veterinary clinic, a pet shop, or a corporate with pet-owning employees, we have a partnership model that works."],
        'types' => [
            ['icon' => 'medical', 'title' => 'Veterinary Clinics', 'desc' => 'Cross-referral partnerships with vet clinics across Abuja  -  ensuring continuity of care for shared patients.'],
            ['icon' => 'partnership', 'title' => 'Pet Retailers', 'desc' => 'Partner with pet shops and suppliers to offer our clients exclusive product discounts and bundled services.'],
            ['icon' => 'pets', 'title' => 'Breeders', 'desc' => 'We work with licensed breeders to provide early socialisation and health checks for new litters.'],
            ['icon' => 'partnership', 'title' => 'Corporate Partners', 'desc' => 'Corporate employee benefit packages  -  discounted Waggies services for your pet-owning staff.'],
            ['icon' => 'boarding', 'title' => 'Property Developers', 'desc' => 'Partner with residential developers to offer Waggies services to residents as a convenient amenity.'],
            ['icon' => 'community', 'title' => 'NGOs & Rescue Orgs', 'desc' => 'We support animal rescue and welfare NGOs with discounted services and pro bono care where we can.'],
        ],
        'cta' => ['heading' => 'Interested in partnering with us?', 'body' => "We'd love to explore how we can work together. Get in touch to start the conversation.", 'ctaLabel' => 'Get in Touch', 'ctaRoute' => 'contact', 'ctaIcon' => 'arrow-forward'],
    ],
];
