<?php

return [
    'currency' => 'NGN',

    'max_service_items' => 12,

    'discounts' => [
        'multiple_pet' => [
            'enabled' => false,
            'percentage' => 10,
            'applies_to' => ['boarding'],
            'applies_from_pet' => 2,
            'calculation' => 'manual_during_quotation',
            'public_label' => 'Multi-pet discounts available and applied during quotation.',
        ],
    ],

    'services' => [
        'boarding' => [
            'label' => 'Boarding',
            'description' => 'Overnight boarding for dogs and cats, priced per pet per night.',
            'enabled' => true,
            'booking_enabled' => true,
            'pricing_enabled' => true,
            'pricing_mode' => 'per_pet_per_night',
            'unit' => 'per pet per night',
            'pet_types' => ['dog', 'cat'],
            'variants' => [
                'dogs' => [
                    'label' => 'Dogs',
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog'],
                    'size_rates' => [
                        'small' => [
                            'label' => 'Small',
                            'booking_label' => 'Small — up to 10kg',
                            'guidance' => 'Up to 10kg',
                            'min_weight_kg' => 0,
                            'min_weight_inclusive' => true,
                            'max_weight_kg' => 10,
                            'max_weight_inclusive' => true,
                            'amount' => 8000,
                            'max_amount' => 12000,
                        ],
                        'medium' => [
                            'label' => 'Medium',
                            'booking_label' => 'Medium — over 10kg through 25kg',
                            'guidance' => 'Over 10kg through 25kg',
                            'min_weight_kg' => 10,
                            'min_weight_inclusive' => false,
                            'max_weight_kg' => 25,
                            'max_weight_inclusive' => true,
                            'amount' => 12000,
                            'max_amount' => 18000,
                        ],
                        'large' => [
                            'label' => 'Large',
                            'booking_label' => 'Large — over 25kg through 40kg',
                            'guidance' => 'Over 25kg through 40kg',
                            'min_weight_kg' => 25,
                            'min_weight_inclusive' => false,
                            'max_weight_kg' => 40,
                            'max_weight_inclusive' => true,
                            'amount' => 18000,
                            'max_amount' => 28000,
                        ],
                        'manual-review' => [
                            'label' => 'Manual review',
                            'booking_label' => 'Above 40kg or unusual size — staff review',
                            'guidance' => 'Above 40kg or unusual size requires manual review.',
                            'min_weight_kg' => 40,
                            'min_weight_inclusive' => false,
                            'max_weight_kg' => null,
                            'max_weight_inclusive' => false,
                            'manual_review' => true,
                        ],
                    ],
                ],
                'cats' => [
                    'label' => 'Cats',
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['cat'],
                    'nightly_rate' => null,
                    'manual_quote' => true,
                    'pricing_note' => 'Cat nightly rate requires staff confirmation before a booking is confirmed.',
                ],
            ],
            'inclusions' => [
                'Individual enclosure',
                'Water',
                'Owner-supplied food and feeding instructions',
                'Routine cleaning',
                'Basic welfare checks',
                'Light bath or wash for boarded dogs before pickup where safe and appropriate',
            ],
            'special_care_note' => 'Medication, special handling, intensive supervision, and other special-care needs require staff review and may carry a separate charge or quote.',
            'food_note' => 'Owner-supplied food is the default. Approved food may be provided only after confirmation, with any applicable cost handled manually.',
        ],
        'vet-care' => [
            'label' => 'Veterinary Care',
            'description' => 'Request veterinary care for dogs and cats, with clinical review before confirmation.',
            'enabled' => true,
            'booking_enabled' => true,
            'pricing_enabled' => true,
            'pricing_mode' => 'service_request',
            'unit' => 'per request',
            'pet_types' => ['dog', 'cat'],
            'variants' => [
                'wellness-consultation' => [
                    'label' => 'Wellness consultation',
                    'type' => 'fixed',
                    'amount' => 12000,
                    'max_amount' => 12000,
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog', 'cat'],
                ],
                'comprehensive-examination' => [
                    'label' => 'Comprehensive examination',
                    'type' => 'fixed',
                    'amount' => 18000,
                    'max_amount' => 18000,
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog', 'cat'],
                ],
                'vaccination-request' => [
                    'label' => 'Vaccination request',
                    'type' => 'quote',
                    'request_only' => true,
                    'description' => 'The veterinary team confirms the appropriate vaccine, assessment, administration, and any record or certificate costs.',
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog', 'cat'],
                ],
                'microchip' => [
                    'label' => 'Microchip implantation',
                    'category' => 'Identification',
                    'type' => 'quote',
                    'request_only' => true,
                    'description' => 'Standalone microchipping is available by request and is reviewed by the veterinary team.',
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog', 'cat'],
                ],
            ],
        ],
        'relocation' => [
            'label' => 'Relocation',
            'description' => 'Custom-quoted import and export coordination for dogs and cats.',
            'enabled' => true,
            'booking_enabled' => true,
            'pricing_enabled' => true,
            'pricing_mode' => 'manual_quote',
            'unit' => 'custom quote',
            'pet_types' => ['dog', 'cat'],
            'variants' => [
                'import' => [
                    'label' => 'Import',
                    'type' => 'quote',
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog', 'cat'],
                ],
                'export' => [
                    'label' => 'Export',
                    'type' => 'quote',
                    'enabled' => true,
                    'booking_enabled' => true,
                    'pricing_enabled' => true,
                    'pet_types' => ['dog', 'cat'],
                ],
            ],
        ],
    ],
];
