<?php

return [
    'import' => [
        'metaTitle' => 'Import a Pet to Nigeria',
        'description' => 'Full-service pet import to Nigeria — permits, health certificates, microchip verification, and airport collection in Abuja.',
        'ogTitle' => 'Import Pets to Nigeria - Waggies Abuja',
        'hero' => ['imageSrc' => '/media/editorial/photo-1606567595334-d39972c85dbe.jpg', 'imageAlt' => 'Pet prepared for import travel', 'eyebrow' => 'Pet Import · Nigeria', 'title' => 'Bringing Your Pet<br/>to Nigeria?', 'description' => 'We manage every import requirement  -  from advance permits and health certificates to airport collection and quarantine coordination.', 'actions' => [['label' => 'Get Estimate', 'route' => 'services.pricing', 'params' => ['service' => 'relocation', 'tier' => 'import'], 'icon' => 'calculator'], ['label' => 'View Checklist', 'route' => 'relocation.checklist']]],
        'sectionHeading' => ['eyebrow' => 'Import Process', 'title' => 'What We Handle<br/>for You', 'subtitle' => 'Importing a pet to Nigeria involves strict documentation and coordination. We take care of every step.'],
        'features' => [
            ['icon' => 'document', 'title' => 'Import Permit', 'desc' => 'We obtain the required import permits from Nigerian veterinary and customs authorities on your behalf.'],
            ['icon' => 'vaccination', 'title' => 'Health & Vaccination Checks', 'desc' => "Review of your pet's vaccination records to confirm compliance with Nigerian import requirements."],
            ['icon' => 'microchip', 'title' => 'Microchip Verification', 'desc' => 'Confirmation that your pet\'s microchip meets the ISO standard required for entry.'],
            ['icon' => 'airport-arrival', 'title' => 'Airport Collection', 'desc' => 'Our team collects your pet from the cargo terminal and handles all on-arrival documentation.'],
            ['icon' => 'home', 'title' => 'Post-Arrival Care', 'desc' => 'Optional post-arrival boarding and health check while your pet settles into their new home.'],
            ['icon' => 'coordinator', 'title' => 'Dedicated Coordinator', 'desc' => 'One point of contact throughout  -  keeping you informed every step of the way.'],
        ],
        'processHeading' => ['eyebrow' => 'How It Works', 'title' => 'A clear path to arrival', 'subtitle' => 'We keep the moving parts visible, with a named next step at every stage.'],
        'processSteps' => [
            ['step' => '01', 'title' => 'Confirm entry requirements', 'description' => 'We review your destination, timeline, and the documents needed before your pet travels to Nigeria.'],
            ['step' => '02', 'title' => 'Prepare permits and health records', 'description' => 'We coordinate import permits, vaccination records, microchip checks, and the required veterinary paperwork.'],
            ['step' => '03', 'title' => 'Coordinate arrival', 'description' => 'We align airport collection, customs handling, and optional post-arrival care around your arrival plan.'],
        ],
        'cta' => ['eyebrow' => 'Timeline assurance', 'heading' => "Ready to start your pet's import process?", 'body' => 'We recommend reaching out at least 4-6 weeks before your intended travel date to ensure all Ministry import permits and rabies titer documentation are processed smoothly.', 'primaryLabel' => 'Request Quote', 'primaryRoute' => 'contact', 'primaryParams' => ['intent' => 'quote', 'service' => 'relocation-import'], 'secondaryLabel' => 'View Checklist', 'secondaryRoute' => 'relocation.checklist'],
    ],
    'export' => [
        'metaTitle' => 'Export a Pet from Nigeria',
        'description' => 'Full-service pet export from Nigeria — health certificates, IATA crates, export permits, and airline coordination.',
        'ogTitle' => 'Export Pets from Nigeria - Waggies Abuja',
        'hero' => ['imageSrc' => '/media/editorial/photo-1552053831-71594a27632d.jpg', 'imageAlt' => 'Dog prepared for international export', 'eyebrow' => 'Pet Export · Nigeria', 'title' => 'Moving Abroad<br/>with Your Pet?', 'description' => 'We manage health certificates, export permits, IATA-approved crates, and airline coordination for a smooth international departure.', 'actions' => [['label' => 'Get Estimate', 'route' => 'services.pricing', 'params' => ['service' => 'relocation', 'tier' => 'export'], 'icon' => 'calculator'], ['label' => 'View Checklist', 'route' => 'relocation.checklist']]],
        'sectionHeading' => ['eyebrow' => 'Export Process', 'title' => 'Everything Covered<br/>Before Departure', 'subtitle' => 'Exporting a pet from Nigeria requires careful planning. We handle it all so your pet travels safely.'],
        'features' => [
            ['icon' => 'document', 'title' => 'Export Health Certificate', 'desc' => 'Our vet issues an official government-endorsed health certificate valid for international travel.'],
            ['icon' => 'vaccination', 'title' => 'Vaccination Compliance', 'desc' => "Review and update of vaccinations to meet the destination country's entry requirements."],
            ['icon' => 'supplies', 'title' => 'IATA-Approved Crate', 'desc' => 'Supply and sizing of an IATA-compliant travel crate appropriate for your pet and the airline.'],
            ['icon' => 'airport-departure', 'title' => 'Airline Booking', 'desc' => 'We liaise with the airline to book your pet as cabin or cargo, and manage all airline paperwork.'],
            ['icon' => 'microchip', 'title' => 'Microchip & Passport', 'desc' => 'Verification of microchip and preparation of a pet passport where required by the destination.'],
            ['icon' => 'coordinator', 'title' => 'Destination Guidance', 'desc' => 'Guidance on entry requirements at your destination country  -  so there are no surprises on arrival.'],
        ],
        'processHeading' => ['eyebrow' => 'How It Works', 'title' => 'A calmer route to departure', 'subtitle' => 'Your documents, crate, and airline handoff are coordinated against the travel date.'],
        'processSteps' => [
            ['step' => '01', 'title' => 'Plan the route', 'description' => 'We review the destination rules, airline options, and the lead time needed for your travel date.'],
            ['step' => '02', 'title' => 'Complete vet and travel documents', 'description' => 'We coordinate health certification, vaccination checks, microchip records, and export paperwork.'],
            ['step' => '03', 'title' => 'Prepare for departure', 'description' => 'We arrange the IATA-compliant crate, airline booking, airport handoff, and destination guidance.'],
        ],
        'cta' => ['eyebrow' => 'Global compliance', 'heading' => 'Planning an international move from Nigeria?', 'body' => 'Different destinations require varying preparation windows — for example, the UK/EU require a rabies blood titer test done 3+ months prior. Contact our team early to stay on schedule.', 'primaryLabel' => 'Request Quote', 'primaryRoute' => 'contact', 'primaryParams' => ['intent' => 'quote', 'service' => 'relocation-export'], 'secondaryLabel' => 'View Checklist', 'secondaryRoute' => 'relocation.checklist'],
    ],
    'transport' => [
        'metaTitle' => 'Local Transport',
        'description' => 'Air-conditioned, door-to-door pet transport and pickup across Abuja by trained handlers. Part of Waggies relocation services.',
        'ogTitle' => 'Local Transport Abuja - Waggies',
        'hero' => ['imageSrc' => '/media/editorial/photo-1606567595334-d39972c85dbe.jpg', 'imageAlt' => 'Pet transport service at Waggies Abuja'],
        'ctaText' => 'Request Transport',
        'ctaRoute' => 'contact',
        'ctaParams' => ['intent' => 'transport', 'service' => 'local-transport'],
        'descriptionBlock' => "Whether it's a trip to Waggies for boarding or grooming, a vet visit, or an airport transfer, our trained handlers and climate-controlled vehicles ensure your pet travels safely and comfortably — door to door.",
        'features' => ['Door-to-door collection and return for all Waggies appointments', 'Air-conditioned, climate-controlled vehicles for comfort', 'Approved travel crates and harnesses for secure transit', 'Drivers trained in animal handling and pet first aid', 'Coverage across all major Abuja districts', 'Time slots booked in advance for reliable scheduling', 'Airport pickup and drop-off for arriving/departing pets', 'Same-day transport for urgent vet visits', 'GPS-tracked vehicles for real-time location updates', 'Pet travel health certificate assistance', 'Multi-pet transport for households with several animals', 'Emergency transport available 24/7'],
        'benefits' => ['Trained handlers — not just drivers. Our team knows how to keep pets calm and safe during transit.', 'Climate-controlled vehicles keep your pet comfortable in any Abuja weather — hot or rainy.', 'GPS tracking means you always know exactly where your pet is during the journey.', 'Approved crates and harnesses ensure your pet is safe and secure — never loose in a vehicle.', 'We cover all major districts — Maitama, Wuse, Asokoro, Garki, Gwarinpa, and beyond.', 'Punctual, reliable scheduling so you can plan your day around the pickup time.'],
        'packages' => [
            ['name' => 'City Pet Transfer', 'popular' => false],
            ['name' => 'Vet Transfer', 'popular' => false],
            ['name' => 'Airport Transfer', 'popular' => true],
        ],
        'processSteps' => [
            ['step' => '01', 'title' => 'Share the journey details', 'description' => 'Tell us the pickup address, destination, pet needs, and preferred time so we can confirm the route.'],
            ['step' => '02', 'title' => 'We collect your pet', 'description' => 'A trained handler arrives in a climate-controlled vehicle and completes the handoff with care.'],
            ['step' => '03', 'title' => 'Safe arrival and update', 'description' => 'We deliver your pet to the destination and keep you informed throughout the transfer.'],
        ],
        'safetyStandards' => [
            ['icon' => 'transport', 'title' => 'Climate-Controlled Fleet', 'desc' => 'Every vehicle is fully air-conditioned and fitted specifically for comfortable, temperature-regulated pet travel in Abuja.'],
            ['icon' => 'safety', 'title' => 'Approved Crates & Restraints', 'desc' => 'Pets travel securely in IATA-approved crates or crash-tested harnesses — never unrestrained in a moving vehicle.'],
            ['icon' => 'medical', 'title' => 'Trained Pet Handlers', 'desc' => 'Our drivers are experienced animal handlers trained in low-stress transport, canine behaviour, and pet first aid.'],
            ['icon' => 'location', 'title' => 'GPS Real-Time Tracking', 'desc' => 'Every transport vehicle is equipped with live GPS tracking so our care team and pet parents know location status.'],
        ],
    ],
    'checklist' => [
        'metaTitle' => 'Pet Relocation Checklist',
        'description' => 'Comprehensive step-by-step checklist for relocating your pet internationally - from 3 months out to the day of travel.',
        'ogTitle' => 'Pet Relocation Checklist - Waggies',
        'hero' => ['imageSrc' => '/media/editorial/photo-1548199973-03cce0bbc87b.jpg', 'imageAlt' => 'Pet relocation checklist', 'eyebrow' => 'Relocation Checklist', 'eyebrowIcon' => 'checklist', 'title' => 'Your Pet Relocation Checklist', 'description' => 'Stay on top of every requirement. Start early  -  some steps can take weeks to complete.'],
        'phases' => [
            ['heading' => '3+ Months Before Travel', 'icon' => 'calendar', 'items' => ['Research the destination country\'s pet import requirements', 'Confirm your pet is microchipped (ISO 11784/11785 standard)', 'Check vaccination requirements  -  especially rabies', 'Contact Waggies to begin the relocation process', 'Book your travel and confirm airline pet policies']],
            ['heading' => '6-8 Weeks Before Travel', 'icon' => 'document', 'items' => ['Apply for export permit from the Nigerian Federal Department of Livestock', 'Book health examination with our on-site vet', 'Order an IATA-approved travel crate (allow time for crate-training)', 'Confirm destination country quarantine requirements', 'Arrange travel insurance for your pet']],
            ['heading' => '2-4 Weeks Before Travel', 'icon' => 'checklist', 'items' => ['Complete official veterinary health certificate (signed and endorsed)', 'Confirm all vaccinations are within the required validity windows', 'Confirm airline booking  -  cargo or cabin  -  with airline reference', 'Prepare a comfort pack: familiar toy, blanket, and food for travel', 'Check crate sizing meets airline and IATA requirements']],
            ['heading' => 'Day of Travel', 'icon' => 'airport-departure', 'items' => ['Arrive at the airport early  -  cargo check-in takes longer than passenger', 'Carry all original documents in your hand luggage', 'Do not feed your pet within 4 hours of the flight (unless advised otherwise)', 'Attach a "Live Animal" label and your contact details to the crate', 'Confirm collection arrangements at the destination']],
        ],
    ],
];
