@extends('layouts.app')

@php($cartItem = ['productId' => $product['id'], 'name' => $product['name'], 'price' => $product['price'], 'imageSrc' => $product['image']])

@section('content')
<x-waggies.breadcrumb-strip :items="[['label' => 'Shop', 'route' => 'shop.index', 'params' => []], ['label' => $product['name']]]" class="border-b border-primary/5 bg-white" />
<div x-data="waggiesProductDetail(@js($product['id']), @js($cartItem))">
    <section class="bg-surface pb-16 md:pb-24"><div class="page-container"><div class="grid grid-cols-1 gap-10 md:grid-cols-2 md:gap-16">
        <div class="flex flex-col gap-3"><div class="relative aspect-square overflow-hidden rounded-2xl bg-white"><img src="{{ $product['image'] }}" alt="{{ $product['alt'] }}" class="h-full w-full object-cover" />@if($product['badge'])<span class="absolute left-4 top-4 rounded-full bg-primary px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-white">{{ $product['badge'] }}</span>@endif</div>@if(count($product['gallery']))<div class="grid grid-cols-4 gap-3">@foreach($product['gallery'] as $image)<img src="{{ $image['thumb'] }}" alt="{{ $image['alt'] }}" class="aspect-square rounded-xl object-cover" loading="lazy" />@endforeach</div>@endif</div>
        <div class="flex flex-col gap-5"><div><p class="mb-2 text-xs font-medium uppercase tracking-wider text-primary/60">{{ $product['category'] }}</p><h1 class="font-serif text-2xl font-bold leading-tight text-primary-dark md:text-3xl">{{ $product['name'] }}</h1></div><p class="text-2xl font-bold text-primary-dark">₦{{ number_format($product['price']) }}</p><p class="text-sm leading-relaxed text-primary-dark/60">{{ $product['description'] }}</p>
            @if(count($product['features']))<ul class="flex flex-col gap-2">@foreach($product['features'] as $feature)<li class="flex items-start gap-2 text-sm text-primary-dark/70"><x-waggies.icon name="check-circle" size="16" class="mt-0.5 shrink-0 text-primary" />{{ $feature }}</li>@endforeach</ul>@endif
            <p class="inline-flex w-fit rounded-full bg-surface-purple px-3 py-1 text-xs font-semibold text-primary-dark">{{ $product['availabilityLabel'] }}</p><div class="mt-2 flex flex-wrap items-center gap-4"><div class="flex items-center overflow-hidden rounded-full border border-primary/10"><button type="button" @click="decrease()" aria-label="Decrease quantity" class="flex h-11 w-11 items-center justify-center text-primary-dark transition-colors hover:bg-surface-purple focus:outline-none focus:ring-2 focus:ring-primary/60"><x-waggies.icon name="remove" size="18" /></button><span class="w-10 select-none text-center text-sm font-semibold text-primary-dark" aria-live="polite" x-text="quantity" :aria-label="`Quantity: ${quantity}`">1</span><button type="button" @click="increase()" aria-label="Increase quantity" class="flex h-11 w-11 items-center justify-center text-primary-dark transition-colors hover:bg-surface-purple focus:outline-none focus:ring-2 focus:ring-primary/60"><x-waggies.icon name="add" size="18" /></button></div><x-waggies.button type="button" @click="addToCart()"><x-waggies.icon name="add-to-cart" size="16" />Add to saved list</x-waggies.button><x-waggies.button href="{{ route('contact', ['intent' => 'product-inquiry', 'product' => $product['id'], 'productName' => $product['name']]) }}" variant="secondary">Ask About This Product</x-waggies.button></div>
            <a href="{{ route('shop.index') }}" class="mt-4 inline-flex w-fit items-center gap-1.5 text-sm font-medium text-primary transition-colors hover:text-primary-dark"><x-waggies.icon name="arrow-back" size="16" />Back to Shop</a>
        </div>
    </div></div></section>
    @if(count($relatedProducts))<section class="bg-white pb-20 md:pb-28"><div class="page-container"><h2 class="mb-10 text-center font-serif text-2xl font-bold text-primary-dark md:text-3xl">You May Also Like</h2><div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">@foreach($relatedProducts as $related)<x-waggies.shop-product-card :product="$related" />@endforeach</div></div></section>@endif
    <section x-data="waggiesRecentlyViewed(@js($product['id']))" x-show="hasVisible()" x-cloak class="bg-surface pb-20 md:pb-28"><div class="page-container"><h2 class="mb-8 font-serif text-2xl font-bold text-primary-dark">Recently Viewed</h2><div class="scrollbar-thin flex gap-6 overflow-x-auto pb-4">@foreach($recentProducts as $recent)<div x-show="isVisible('{{ $recent['id'] }}')" x-cloak class="w-64 shrink-0"><x-waggies.shop-product-card :product="$recent" /></div>@endforeach</div></div></section>
</div>
@endsection
