@extends('layouts.app')
@section('content')
<x-waggies.breadcrumb-strip :items="[['label' => 'About']]" class="border-b border-primary/5 bg-white" />
<x-waggies.cover-hero :hero="$hero">
    <x-slot:supporting>
        <span class="inline-flex items-center gap-2 rounded-full border border-surface-purple bg-white px-4 py-1.5 shadow-sm">
            <x-waggies.icon name="star" variant="filled" size="18" class="text-gold" />
            <span class="text-xs font-bold text-primary-dark">4.9 · 500+ Reviews</span>
            <span class="h-2 w-2 rounded-full bg-primary" aria-hidden="true"></span>
        </span>
    </x-slot:supporting>
</x-waggies.cover-hero>

<section class="relative z-30 -mt-8 mx-4 max-w-[1200px] rounded-2xl border border-primary/12 bg-white shadow-soft sm:mx-10 lg:mx-auto"><div class="grid grid-cols-2 gap-0 divide-x divide-y divide-primary/10 sm:px-4 md:grid-cols-4 md:divide-y-0">@foreach($stats as $stat)<div class="flex min-h-32 flex-col justify-center px-5 py-6 text-center sm:px-7"><span class="font-serif text-4xl font-bold leading-none text-primary">{{ $stat['value'] }}</span><span class="mt-2 text-label text-primary-dark/55">{{ $stat['label'] }}</span></div>@endforeach</div></section>

<section class="bg-surface py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><div class="flex flex-col items-center gap-16 lg:flex-row lg:gap-24"><div class="lg:w-1/2"><div class="mb-4 flex items-center gap-3"><span class="h-px w-8 bg-primary" aria-hidden="true"></span><p class="text-label text-primary">{{ $philosophy['eyebrow'] }}</p></div><h2 class="text-h2 mb-6 leading-tight text-primary-dark">{{ $philosophy['title'] }}</h2><div class="space-y-5 text-body">@foreach($philosophy['body'] as $p)<p>{{ $p }}</p>@endforeach</div><div class="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2">@foreach($philosophy['features'] as $feature)<div class="flex items-start gap-3"><div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-surface-purple text-primary"><x-waggies.icon name="{{ $feature['icon'] }}" size="19" /></div><div><h3 class="text-h4 text-primary-dark">{{ $feature['title'] }}</h3><p class="text-body-sm mt-0.5">{{ $feature['description'] }}</p></div></div>@endforeach</div></div><div class="w-full lg:w-1/2"><div class="grid grid-cols-2 gap-4">@foreach($mosaicImages as $image)<div class="rounded-2xl shadow-sm transition hover:shadow-soft @if(!empty($image['offset'])) mt-8 @endif"><img src="{{ $image['src'] }}" alt="{{ $image['alt'] }}" class="h-64 w-full rounded-2xl object-cover" loading="lazy"></div>@endforeach</div></div></div></div></section>

<section class="bg-white py-20"><div class="mx-auto grid max-w-7xl grid-cols-1 items-center gap-16 px-4 md:px-10 lg:grid-cols-2 lg:px-12"><div><h2 class="text-h2 mb-5 leading-tight text-primary-dark">{!! $story['title'] !!}</h2>@foreach($story['paragraphs'] as $paragraph)<p class="text-body @if(!$loop->last) mb-4 @endif">{{ $paragraph }}</p>@endforeach</div><div class="grid grid-cols-2 gap-4">@foreach($story['stats'] as $stat)<div class="rounded-2xl bg-surface-purple p-6 text-center"><span class="mb-1 block font-serif text-4xl font-bold text-primary">{{ $stat['value'] }}</span><span class="text-label text-primary-dark/50">{{ $stat['label'] }}</span></div>@endforeach</div></div></section>

<section class="w-full bg-primary-dark py-24 text-white"><div class="mx-auto grid max-w-7xl grid-cols-1 items-center gap-16 px-4 md:px-10 lg:grid-cols-2 lg:px-12"><div class="flex max-w-xl flex-col gap-6"><p class="text-secondary text-xs font-bold uppercase tracking-widest">{{ $standards['eyebrow'] }}</p><h2 class="font-serif text-3xl font-bold leading-tight md:text-4xl">{!! $standards['title'] !!}</h2><p class="text-base leading-relaxed text-white/70">{{ $standards['subtitle'] }}</p></div><div class="flex flex-col gap-5">@foreach($standards['features'] as $feature)<div class="flex items-start gap-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5 transition hover:bg-white/[0.06]"><div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-white/10 text-secondary"><x-waggies.icon name="{{ $feature['icon'] }}" size="19" /></div><div><h3 class="font-serif text-lg font-bold text-white">{{ $feature['title'] }}</h3><p class="mt-1 text-sm leading-relaxed text-white/60">{{ $feature['description'] }}</p></div></div>@endforeach</div></div></section>

<section class="bg-surface py-20"><div class="mx-auto max-w-7xl px-4 md:px-10 lg:px-12"><div class="mb-14 text-center"><p class="text-label mb-3 text-primary">{{ $teamHeading['eyebrow'] }}</p><h2 class="text-h2 mb-4 text-primary-dark">{{ $teamHeading['title'] }}</h2><p class="text-body-sm mx-auto max-w-lg">{{ $teamHeading['intro'] }}</p></div><div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 lg:gap-7">@foreach($team as $member)<div class="flex flex-col items-center rounded-xl bg-white p-6 text-center shadow-sm transition hover:shadow-soft @if(!empty($member['placeholder'])) border-2 border-dashed border-primary/20 @else border border-primary/5 @endif"><div class="h-28 w-28 shrink-0 overflow-hidden rounded-full bg-surface-purple sm:h-32 sm:w-32"><img src="{{ $member['imageSrc'] }}" alt="{{ $member['imageAlt'] }}" class="h-full w-full object-cover" loading="lazy"></div><div class="mt-4 space-y-1"><div class="flex items-center justify-center gap-2"><h3 class="font-serif text-base font-bold leading-tight text-primary-dark sm:text-lg">{{ $member['name'] }}</h3>@if(!empty($member['verified']))<x-waggies.icon name="verified" variant="filled" size="17" class="shrink-0 text-primary" />@endif</div><p class="text-label font-medium text-primary">{{ $member['role'] }}</p>@if(!empty($member['responsibility']))<p class="text-meta pt-1 leading-relaxed text-primary-dark/60">{{ $member['responsibility'] }}</p>@endif</div></div>@endforeach</div></div></section>

<section class="border-t border-surface-purple bg-white py-16"><div class="mx-auto max-w-3xl px-4 text-center md:px-10"><h2 class="text-h3 mb-3 text-primary-dark">Visit Us</h2><p class="mb-6 text-primary-dark/70">{{ $address }}</p><a href="{{ route('contact') }}" class="w-cta w-cta--primary">Get Directions &amp; Contact Details <x-waggies.icon name="arrow-forward" size="17" /></a></div></section>
<section class="border-t border-surface-purple bg-white py-16"><div class="mx-auto max-w-7xl px-4 md:px-8"><div class="relative w-full overflow-hidden rounded-2xl bg-surface-purple"><div class="relative mx-auto flex max-w-5xl flex-col gap-10 px-4 py-12 md:flex-row md:items-center md:justify-between md:px-10 md:py-16"><div class="max-w-xl text-center md:text-left"><h2 class="font-serif text-3xl font-bold leading-tight text-primary-dark">{{ $cta['heading'] }}</h2><p class="mt-5 max-w-md text-base leading-relaxed text-primary-dark/65">{{ $cta['body'] }}</p></div><div><a href="{{ route('services.index') }}" class="w-cta w-cta--primary">{{ $cta['label'] }} <x-waggies.icon name="arrow-forward" size="16" /></a></div></div></div></div></section>

@endsection
