@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Cost Calculator']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.page-header alignment="center" eyebrow="Pet Care Tool" eyebrow-icon="calculator" title="Cost Calculator" description="Get a quick estimate for Waggies services based on your pet's type, size, and the service you need." />
    <section class="bg-surface pb-20 md:pb-28">
        <div x-data="costCalculator(@js($costCalculator))" class="mx-auto max-w-2xl px-4 md:px-10">
            <div class="flex flex-col gap-8">
                <div class="rounded-2xl border border-primary/10 bg-white p-6"><h3 class="mb-5 font-serif text-lg font-bold text-primary-dark">Pet Type</h3><div class="grid grid-cols-2 gap-3"><button type="button" @click="setPetType('dog')" class="flex items-center justify-center gap-2 rounded-xl border-2 p-4 font-semibold transition-colors" :class="petType === 'dog' ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'"><x-waggies.icon name="pets" size="24" />Dog</button><button type="button" @click="setPetType('cat')" class="flex items-center justify-center gap-2 rounded-xl border-2 p-4 font-semibold transition-colors" :class="petType === 'cat' ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'"><x-waggies.icon name="cat" size="24" />Cat</button></div></div>
                <div class="rounded-2xl border border-primary/10 bg-white p-6"><h3 class="mb-5 font-serif text-lg font-bold text-primary-dark">Pet Size</h3><div class="grid grid-cols-2 gap-3 md:grid-cols-3"><template x-for="size in validSizes()" :key="size"><button type="button" @click="petSize = size" class="flex flex-col items-start gap-0.5 rounded-xl border-2 p-4 text-left transition-colors" :class="effectiveSize() === size ? 'border-primary bg-surface-purple' : 'border-primary/10 bg-white hover:border-primary/30'"><span class="font-semibold" :class="effectiveSize() === size ? 'text-primary' : 'text-primary-dark/80'" x-text="size.charAt(0).toUpperCase() + size.slice(1)"></span><span class="text-xs text-primary-dark/50" x-text="petTypes[petType].labels[size]"></span></button></template></div></div>
                <div class="rounded-2xl border border-primary/10 bg-white p-6"><h3 class="mb-5 font-serif text-lg font-bold text-primary-dark">Service Type</h3><div class="grid grid-cols-2 gap-3"><button type="button" @click="service = 'boarding'" class="flex items-center gap-3 rounded-xl border-2 p-4 text-left transition-colors" :class="service === 'boarding' ? 'border-primary bg-surface-purple' : 'border-primary/10 bg-white hover:border-primary/30'"><span :class="service === 'boarding' ? 'text-primary' : 'text-primary-dark/60'"><x-waggies.icon name="boarding" size="20" /></span><div><p class="text-sm font-semibold" :class="service === 'boarding' ? 'text-primary' : 'text-primary-dark/80'">Boarding</p><p class="text-xs text-primary-dark/60">Per night</p></div></button><button type="button" @click="service = 'grooming'" class="flex items-center gap-3 rounded-xl border-2 p-4 text-left transition-colors" :class="service === 'grooming' ? 'border-primary bg-surface-purple' : 'border-primary/10 bg-white hover:border-primary/30'"><span :class="service === 'grooming' ? 'text-primary' : 'text-primary-dark/60'"><x-waggies.icon name="grooming" size="20" /></span><div><p class="text-sm font-semibold" :class="service === 'grooming' ? 'text-primary' : 'text-primary-dark/80'">Grooming</p><p class="text-xs text-primary-dark/60">Per session</p></div></button><button type="button" @click="service = 'vet'" class="flex items-center gap-3 rounded-xl border-2 p-4 text-left transition-colors" :class="service === 'vet' ? 'border-primary bg-surface-purple' : 'border-primary/10 bg-white hover:border-primary/30'"><span :class="service === 'vet' ? 'text-primary' : 'text-primary-dark/60'"><x-waggies.icon name="veterinary-care" size="20" /></span><div><p class="text-sm font-semibold" :class="service === 'vet' ? 'text-primary' : 'text-primary-dark/80'">Vet Care</p><p class="text-xs text-primary-dark/60">Per visit</p></div></button><button type="button" @click="service = 'training'" class="flex items-center gap-3 rounded-xl border-2 p-4 text-left transition-colors" :class="service === 'training' ? 'border-primary bg-surface-purple' : 'border-primary/10 bg-white hover:border-primary/30'"><span :class="service === 'training' ? 'text-primary' : 'text-primary-dark/60'"><x-waggies.icon name="training" size="20" /></span><div><p class="text-sm font-semibold" :class="service === 'training' ? 'text-primary' : 'text-primary-dark/80'">Training</p><p class="text-xs text-primary-dark/60">Per session</p></div></button></div></div>
                <div x-show="service === 'boarding'" class="rounded-2xl border border-primary/10 bg-white p-6"><h3 class="mb-2 font-serif text-lg font-bold text-primary-dark">Duration</h3><p class="mb-5 text-sm text-primary-dark/50">Number of nights for boarding</p><div class="flex items-center gap-4"><button type="button" @click="duration = Math.max(1, duration - 1)" class="flex h-10 w-10 items-center justify-center rounded-full border border-primary/20 text-primary transition-colors hover:bg-surface-purple"><x-waggies.icon name="remove" size="18" /></button><span class="w-24 text-center font-serif text-3xl font-bold text-primary-dark" x-text="duration"></span><button type="button" @click="duration = Math.min(30, duration + 1)" class="flex h-10 w-10 items-center justify-center rounded-full border border-primary/20 text-primary transition-colors hover:bg-surface-purple"><x-waggies.icon name="add" size="18" /></button><span class="text-sm text-primary-dark/50" x-text="duration === 1 ? 'night' : 'nights'"></span></div></div>
                <div class="rounded-2xl border-2 border-primary/20 bg-white p-8 text-center"><x-waggies.icon name="payments" size="36" class="mb-3 text-primary" /><p class="mb-2 text-sm font-bold uppercase tracking-wider text-primary-dark/50">Estimated Cost</p><p class="mb-1 font-serif text-3xl font-bold text-primary-dark md:text-4xl"><span x-text="formatNaira(estimate().min)"></span> &ndash; <span x-text="formatNaira(estimate().max)"></span></p><p class="mb-6 text-sm text-primary-dark/50"><span x-text="services[service].label"></span><span x-text="service === 'boarding' ? ' × ' + duration + ' nights' : ' (per session)'"></span> · <span x-text="petTypes[petType].labels[effectiveSize()]"></span></p><div class="flex items-start gap-2.5 rounded-xl bg-secondary/30 p-4 text-left"><x-waggies.icon name="info" size="18" class="mt-0.5 shrink-0 text-primary" /><p class="text-xs leading-relaxed text-primary-dark/50">Estimates only. Contact us for an accurate quote. Prices vary based on your pet&rsquo;s specific needs and the services selected.</p></div></div>
            </div>
            <x-waggies.tool-cta tool-route="tools.cost" />
        </div>
    </section>
@endsection
