@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Emergency & Poison Guide']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.page-header alignment="center" eyebrow="Pet Care Tool" eyebrow-icon="emergency" title="Emergency & Poison Guide" description="Quick-reference for dogs and cats. If your pet may be seriously unwell, contact a veterinarian or emergency service immediately." />
    <section class="bg-surface pb-20 md:pb-28"><div class="mx-auto max-w-4xl px-4 md:px-10">
        <x-waggies.medical-disclaimer />
        <div class="mt-6 rounded-2xl border border-red-200/70 bg-red-50 p-5 sm:p-6"><div class="flex items-start gap-3"><x-waggies.icon name="warning" size="23" variant="filled" class="mt-0.5 shrink-0 text-red-600" /><div><h2 class="font-serif text-xl font-bold text-red-950">Need urgent help?</h2><p class="mt-1 text-sm leading-relaxed text-red-900/75">Call Waggies or your nearest emergency veterinary service. This guide is not a diagnosis.</p></div></div><div class="mt-4 flex flex-col gap-3 sm:flex-row"><x-waggies.button href="tel:{{ preg_replace('/\s+/', '', config('waggies.phone_international')) }}" class="gap-1.5 px-6 py-3 text-sm"><x-waggies.icon name="phone" size="17" />Call {{ config('waggies.phone') }}</x-waggies.button><x-waggies.button href="{{ config('waggies.whatsapp') }}?text=Emergency%20-%20My%20pet%20needs%20help" variant="secondary" target="_blank" rel="noreferrer" class="gap-1.5 px-6 py-3 text-sm">WhatsApp emergency</x-waggies.button></div></div>
        <p class="mt-6 text-sm text-primary-dark/60">These records are marked <strong>SEED_CONTENT</strong> and <strong>REQUIRES_CLINICAL_REVIEW</strong> for future CMS replacement.</p>
        <div class="mt-6 space-y-5">@foreach(config('waggies_tools.emergency') as $record)<article class="rounded-2xl border border-primary/10 bg-white p-5 sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[0.12em] text-primary/55">{{ $record['species'] === 'both' ? 'Dogs and cats' : $record['species'] }} · {{ $record['category'] }}</p><h2 class="mt-1 font-serif text-xl font-bold text-primary-dark">{{ $record['title'] }}</h2></div><span class="rounded-full bg-red-50 px-3 py-1 text-xs font-bold uppercase tracking-[0.12em] text-red-800">{{ $record['severity'] }}</span></div><div class="mt-5 grid gap-5 md:grid-cols-3"><div><h3 class="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-primary/60"><x-waggies.icon name="warning" size="15" class="text-amber-600" />Symptoms</h3><ul class="mt-3 space-y-2">@foreach($record['symptoms'] as $item)<li class="text-sm leading-relaxed text-primary-dark/65">{{ $item }}</li>@endforeach</ul></div><div><h3 class="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-primary/60"><x-waggies.icon name="check-circle" size="15" class="text-emerald-700" />Do now</h3><ul class="mt-3 space-y-2">@foreach($record['actions'] as $item)<li class="text-sm leading-relaxed text-primary-dark/65">{{ $item }}</li>@endforeach</ul></div><div><h3 class="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-primary/60"><x-waggies.icon name="privacy" size="15" class="text-red-700" />Avoid</h3><ul class="mt-3 space-y-2">@foreach($record['avoid'] as $item)<li class="text-sm leading-relaxed text-primary-dark/65">{{ $item }}</li>@endforeach</ul></div></div></article>@endforeach</div>
        <x-waggies.tool-cta medical tool-route="tools.emergency" />
    </div></section>
@endsection
