@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Medication Dosage Guide']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.page-header alignment="center" eyebrow="Pet Care Tool" eyebrow-icon="medication" title="Medication & OTC Safety Guide" description="Safety-first information about formulations, jurisdiction, human medication risks, and when veterinary help is needed." />
    <section class="bg-surface pb-20 md:pb-28"><div class="mx-auto max-w-3xl px-4 md:px-10">
        <x-waggies.medical-disclaimer />
        <div class="mt-8 rounded-2xl border border-red-200 bg-red-50 p-6 sm:p-8"><h2 class="font-serif text-lg font-bold text-red-950 sm:text-xl">Do not give human pain medicine without veterinary instruction</h2><p class="mt-2 text-sm leading-relaxed text-red-900">Ibuprofen, naproxen, aspirin, paracetamol/acetaminophen, and combination products can be dangerous to pets. Weight alone does not make a medicine safe. If ingestion may have occurred, contact a veterinarian urgently and keep the packaging.</p></div>
        <div class="mt-8 space-y-4">@foreach([['title' => 'Structured medication references', 'icon' => 'medication', 'description' => 'A medication may be shown only with explicit species, indication, formulation, strength, route, jurisdiction, source, and clinical review.'], ['title' => 'Product and label context', 'icon' => 'guide', 'description' => 'A Nigerian registration or label is product information. It is not a Waggies recommendation or proof that the product suits a particular pet.'], ['title' => 'Dose display gate', 'icon' => 'verified', 'description' => 'Unreviewed, incomplete, conflicting, or withdrawn dosage information is withheld and replaced with veterinary escalation.']] as $section)<div class="flex items-start gap-4 rounded-xl border border-primary/10 bg-white p-5 sm:p-6"><div class="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-surface-purple"><x-waggies.icon name="{{ $section['icon'] }}" size="28" class="text-primary" /></div><div><h3 class="font-serif text-base font-bold text-primary-dark">{{ $section['title'] }}</h3><p class="mt-1 text-sm leading-relaxed text-primary-dark/60">{{ $section['description'] }}</p></div></div>@endforeach</div>
        <x-waggies.tool-cta medical tool-route="tools.medication" />
    </div></section>
@endsection
