@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Nutrition Calculator']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.page-header alignment="center" eyebrow="Pet Care Tool" eyebrow-icon="nutrition" title="Diet &amp; Nutrition Calculator" description="Estimate your pet's daily calorie needs based on weight, species, life stage, and activity level." />
    <section class="bg-surface pb-20 md:pb-28">
        <div x-data="nutritionCalculator" class="mx-auto max-w-2xl px-4 md:px-10">
            <x-waggies.medical-disclaimer variant="compact" />
            <div class="mt-6 space-y-8">
                <div><label class="mb-2 block text-sm font-semibold text-primary-dark">Species</label><div class="grid grid-cols-2 gap-3"><template x-for="option in ['Dog', 'Cat']" :key="option"><button type="button" @click="changeSpecies(option)" class="rounded-xl border p-3 text-center text-sm font-semibold transition" :class="species === option ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'" x-text="option"></button></template></div></div>
                <div><label for="nutrition-weight" class="mb-2 block text-sm font-semibold text-primary-dark">Weight</label><div class="flex gap-3"><input id="nutrition-weight" type="number" min="0.1" step="0.1" x-model="weight" :placeholder="species === 'Dog' ? 'e.g. 15' : 'e.g. 4'" class="min-h-[44px] flex-1 rounded-xl border border-primary/10 bg-white px-4 py-3 text-sm text-primary-dark placeholder:text-primary-dark/30 focus:outline-none focus:ring-2 focus:ring-primary/40" /><div class="flex overflow-hidden rounded-xl border border-primary/10"><template x-for="option in ['kg', 'lb']" :key="option"><button type="button" @click="unit = option" class="px-4 py-3 text-sm font-semibold transition" :class="unit === option ? 'bg-primary text-white' : 'bg-white text-primary-dark/60 hover:bg-primary/5'" x-text="option"></button></template></div></div></div>
                <div><label class="mb-2 block text-sm font-semibold text-primary-dark">Life Stage</label><div class="flex flex-wrap gap-2"><template x-for="stage in stages[species]" :key="stage"><button type="button" @click="lifeStage = stage" class="rounded-full border px-4 py-2 text-sm font-medium transition" :class="lifeStage === stage ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'" x-text="stage"></button></template></div></div>
                <div><label class="mb-2 block text-sm font-semibold text-primary-dark">Activity Level</label><div class="flex flex-wrap gap-2"><template x-for="level in activities" :key="level"><button type="button" @click="activity = level" class="rounded-full border px-4 py-2 text-sm font-medium transition" :class="activity === level ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'" x-text="level"></button></template></div></div>
                <div x-show="result()" x-cloak class="rounded-2xl border border-primary/10 bg-white p-6"><h3 class="font-serif text-lg font-bold text-primary-dark">Estimated starting energy requirement</h3><p class="mt-1 text-sm text-primary-dark/50">Resting Energy Requirement (RER): <span x-text="result()?.rer"></span> kcal/day</p><p class="text-sm text-primary-dark/50">Planning factor (life stage + activity): <span x-text="result()?.multiplier"></span>x</p><div class="mt-4 text-center"><span class="text-4xl font-bold text-primary" x-text="result()?.dailyCalories"></span><span class="ml-2 text-sm text-primary-dark/50">estimated kcal / day</span></div><p class="mt-3 text-center text-xs leading-relaxed text-primary-dark/60">This is a starting estimate using RER = 70 × body weight (kg)^0.75 and a general planning factor. It is not an exact prescription; adjust only with body-condition monitoring and veterinary advice.</p></div>
                <div class="rounded-xl border border-amber-200/60 bg-amber-50 p-4"><p class="text-xs leading-relaxed text-amber-900"><strong>For pets with medical conditions (diabetes, kidney disease, obesity, etc.):</strong> calorie needs differ significantly from standard estimates. Please consult your veterinarian for a personalised feeding plan.</p></div>
            </div>
            <x-waggies.tool-cta tool-route="tools.nutrition" />
        </div>
    </section>
@endsection
