@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Parasite & Deworming Schedule']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.page-header alignment="center" eyebrow="Pet Care Tool" eyebrow-icon="parasite" title="Parasite Prevention Planning" description="Separate parasite risks and plan testing or prevention with a veterinarian; this guide does not prescribe a universal deworming calendar." />
    <section class="bg-surface pb-20 md:pb-28"><div class="mx-auto max-w-2xl px-4 md:px-10">
        <x-waggies.medical-disclaimer /><div class="mt-6 space-y-5"><div class="rounded-2xl border border-primary/10 bg-white p-6"><h2 class="font-serif text-lg font-bold text-primary-dark">What to discuss</h2><ul class="mt-4 space-y-3 text-sm leading-relaxed text-primary-dark/70"><li><strong>Intestinal parasites:</strong> age, stool findings, previous treatment, household exposure, and local risk.</li><li><strong>Heartworm:</strong> geography, travel, mosquito exposure, testing, and the specific product label.</li><li><strong>Fleas and ticks:</strong> species, environment, contact with other animals, product formulation, and label instructions.</li><li><strong>Mites and protozoal disease:</strong> diagnosis and treatment depend on the parasite and should not be collapsed into “deworming”.</li></ul></div><div class="rounded-xl border border-amber-200/60 bg-amber-50 p-4"><p class="text-sm leading-relaxed text-amber-950"><strong>Safety boundary:</strong> Do not give a parasite product based on a generic interval or another pet&apos;s prescription. Product, formulation, concentration, species, weight range, indication, geography, and veterinary advice all matter.</p></div></div>
        <x-waggies.tool-cta medical tool-route="tools.parasite" />
    </div></section>
@endsection
