@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Parasite & Deworming Schedule']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.tool-hero eyebrow="Pet Care Tool" eyebrow-icon="parasite" title="Parasite & Deworming Schedule" subtitle="A general educational timeline for deworming puppies, kittens, and adult pets." />
    <section class="bg-surface pb-20 md:pb-28"><div x-data="{ species: 'dog', timelines: { dog: [{phase:'Puppy Phase',range:'2 weeks - 6 months',steps:[['2 weeks','First deworming dose'],['4 weeks','Second deworming dose'],['6 weeks','Third deworming dose'],['8 weeks','Fourth deworming dose'],['12 weeks','Monthly deworming continues'],['16 weeks','Monthly deworming continues'],['6 months','Monthly deworming concludes; transition to adult schedule']]},{phase:'Adult',range:'6+ months',steps:[['Every 3 months','Regular deworming (at minimum)']]},{phase:'After Travel',range:'As needed',steps:[['Within 2 weeks of return','Deworm after travel to high-risk areas']]}], cat: [{phase:'Kitten Phase',range:'2 weeks - 6 months',steps:[['2 weeks','First deworming dose'],['4 weeks','Second deworming dose'],['6 weeks','Third deworming dose'],['8 weeks','Fourth deworming dose'],['12 weeks','Monthly deworming continues'],['6 months','Monthly deworming concludes; transition to adult schedule']]},{phase:'Adult',range:'6+ months',steps:[['Every 3 months','Regular deworming (at minimum)']]},{phase:'After Travel',range:'As needed',steps:[['Within 2 weeks of return','Deworm after travel to high-risk areas']]}] } }" class="mx-auto max-w-2xl px-4 md:px-10">
        <x-waggies.medical-disclaimer /><div class="mt-6"><div class="space-y-8"><div><label class="mb-2 block text-sm font-semibold text-primary-dark">Species</label><div class="grid grid-cols-2 gap-3"><template x-for="s in ['dog','cat']" :key="s"><button type="button" @click="species=s" class="rounded-xl border p-3 text-center text-sm font-semibold transition" :class="species === s ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'" x-text="s === 'dog' ? 'Dog' : 'Cat'"></button></template></div></div><template x-for="(phase, phaseIdx) in timelines[species]" :key="phase.phase"><div class="rounded-2xl border border-primary/10 bg-white p-5 sm:p-6"><div class="mb-4 flex items-center gap-3"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary text-xs font-bold text-white" x-text="phaseIdx + 1"></span><div><h3 class="font-serif text-base font-bold text-primary-dark" x-text="phase.phase"></h3><p class="text-xs text-primary-dark/50" x-text="phase.range"></p></div></div><div class="ml-4 space-y-4 border-l-2 border-primary/10 pl-5"><template x-for="step in phase.steps" :key="step[0]"><div class="relative"><div class="absolute -left-[1.85rem] top-1 h-3 w-3 rounded-full border-2 border-white bg-primary/30"></div><p class="text-sm font-semibold text-primary-dark" x-text="step[0]"></p><p class="mt-0.5 text-sm text-primary-dark/50" x-text="step[1]"></p></div></template></div></div></template><div class="rounded-xl border border-amber-200/60 bg-amber-50 p-4"><p class="text-xs leading-relaxed text-amber-900"><strong>Important:</strong> Specific products and schedules should be confirmed with your veterinarian. The timeline above is general educational guidance and may vary based on your pet&apos;s health, environment, and local risk factors.</p></div></div></div>
        <x-waggies.tool-cta medical tool-route="tools.parasite" />
    </div></section>
@endsection
