@extends('layouts.app')
@section('content')
    <x-waggies.breadcrumb-strip :items="[['label' => 'Tools', 'route' => 'tools.index'], ['label' => 'Vaccination Schedule']]" class="border-b border-primary/5 bg-white" />
    <x-waggies.page-header alignment="center" eyebrow="Pet Care Tool" title="Vaccination Schedule" description="See the recommended vaccination timeline for your pet. Core vaccines are required; non-core vaccines depend on your pet's lifestyle." />
    <section class="bg-surface pb-20 md:pb-28"><div x-data="{ petType: 'dog', schedules: @js($schedules) }" class="mx-auto max-w-3xl px-4 md:px-10">
        <div class="flex flex-col gap-8">
            <div class="rounded-2xl border border-primary/10 bg-white p-6"><h3 class="mb-5 font-serif text-lg font-bold text-primary-dark">Select Pet Type</h3><div class="grid grid-cols-2 gap-3"><template x-for="pt in ['dog','cat']" :key="pt"><button type="button" @click="petType = pt" class="flex items-center justify-center gap-2 rounded-xl border-2 p-4 font-semibold transition-colors" :class="petType === pt ? 'border-primary bg-surface-purple text-primary' : 'border-primary/10 bg-white text-primary-dark/60 hover:border-primary/30'"><x-waggies.icon name="pets" size="24" /><span x-text="pt === 'dog' ? 'Dog' : 'Cat'"></span></button></template></div></div>
            <div class="flex flex-wrap gap-4 text-sm"><div class="flex items-center gap-2"><span class="h-3 w-3 rounded-full bg-primary"></span><span class="text-primary-dark/60">Core (required)</span></div><div class="flex items-center gap-2"><span class="h-3 w-3 rounded-full border border-secondary bg-secondary"></span><span class="text-primary-dark/60">Non-core (recommended)</span></div></div>
            <div class="relative"><div class="absolute bottom-0 left-5 top-0 hidden w-px bg-primary/15 md:block"></div><div class="flex flex-col gap-6"><template x-for="(entry, idx) in schedules[petType]" :key="entry.age"><div class="relative flex gap-5 md:gap-8"><div class="relative z-10 hidden h-10 w-10 shrink-0 items-center justify-center rounded-full border-2 border-primary bg-white md:flex"><x-waggies.icon name="vaccination" size="18" class="text-primary" /></div><div class="flex-1 rounded-2xl border border-primary/10 bg-white p-5 md:p-6"><div class="mb-4 flex items-center gap-2 md:mb-0"><div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-surface-purple md:hidden"><x-waggies.icon name="vaccination" size="16" class="text-primary" /></div><h3 class="font-serif text-lg font-bold text-primary-dark" x-text="entry.age"></h3></div><div class="mt-3 flex flex-col gap-3"><template x-for="vax in entry.vaccines" :key="vax.name"><div class="rounded-xl p-4" :class="vax.type === 'core' ? 'border border-primary/15 bg-primary/5' : 'border border-secondary bg-secondary/30'"><div class="flex items-start justify-between gap-3"><div class="flex-1"><p class="text-sm font-semibold text-primary-dark" x-text="vax.name"></p><p class="mt-1 text-xs leading-relaxed text-primary-dark/50" x-text="vax.description"></p></div><span class="shrink-0 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider" :class="vax.type === 'core' ? 'bg-primary/10 text-primary' : 'bg-secondary text-primary-dark/60'" x-text="vax.type === 'core' ? 'Core' : 'Non-core'"></span></div></div></template></div></div></div></template></div></div>
        </div>
        <x-waggies.tool-cta medical tool-route="tools.vaccination" />
        <div class="mt-10"><x-waggies.medical-disclaimer /></div>
    </div></section>
@endsection
